### ISSUE TITLE
MaintForumAdmin

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#101]
Super pratique le calendrier ... bien foutu

Dommage que tous les jours de la semaine ne soit pas sur 2 caracteres...
A moins que ce soit mis a jour dans la V6

**Comment by jipexu** [comment]
voilà le choix qu'on a dans les fichiers de trad ...
je ne veux pas modifier car après c'est lourd lors des mises à jours des lib ... donc tu penses que day short serait mieux ?  (mais je ne sais pas si on passe bien sur les petits médias avec des caractères en plus ...
`days:["dimanche","lundi","mardi","mercredi","jeudi","vendredi","samedi"],
daysShort:["dim.","lun.","mar.","mer.","jeu.","ven.","sam."],
daysMin:["d","l","ma","me","j","v","s"],`

**Comment by Jireck-npds** [comment]
Juste sur un ecran 21" une lettre est ... illisible 

quand on prends un windows ou autre les jour sont sur 2 caracteres donc... 

L'idéal serait DayShort en standard et basculer en daymin sur mobile ...

Mais comme je disais ailleurs administrer un site depuis un mobile est un connerie ...
d'une tablette ca doit le fait ...

Voila mon avis ...
Fais comme il te semble

**Comment by jipexu** [comment]
va pour day short ...

**Comment by bmag-npds** [comment]
On a surtout un bug d'affichage sur la ligne sous le bouton Agenda.
les boutons sont tronqué sur mon Nokia
