### ISSUE TITLE
Localhost non supporter

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#156]
Probleme lors de l'install automatique 
lors du config upload 
le champs URL HTTP de votre site ne supporte pas "http://localhost/"

**Comment by jipexu** [comment]
c'est le contrôle du form ??

**Comment by Jireck-npds** [comment]
Surement ca avec un localhost.com ca passe

**Comment by jipexu** [comment]
de mémoire il me semble que l'IP de ton local host doit passer je crois ....

**Comment by Jireck-npds** [comment]
Cela me semble etre un frein aux personnes qui veulent tester en local et qui reste bloquer car le parametres ne passe pas

**Comment by jipexu** [comment]
l'IP du local host passe ou pas ?

**Comment by Jireck-npds** [comment]
Je ne sais pas pour l'instant je test chez moi et la je suis au job...

**Comment by jipexu** [comment]
ok bon tu me dira car il me semble que bmag a tester ca et que ca fonctionnait avec l'ip de localhost ...

**Comment by bmag-npds** [comment]
chez moi ca passe sans problème, apres que j'ai mis un mot de passe pour l'admin de mysql ce que je n'avais jamais eu besoin de faire avant

**Comment by Jireck-npds** [comment]
Le truc c'est que si on laisse comme cela, il faut preciser que pour localhost, il faut mieux mettre 127.0.0.1

**Comment by jipexu** [comment]
oui ! (car ce serait domage de supprimer le controle ....)

**Comment by Jireck-npds** [comment]
Ok tu corrige et tu clos :=> soit un mot soit une modif du controle.
Tu as regardé / testé le header.php ? 
@bmag-npds J'ai propose la modification des blocs via pages sur une pages avec differents OP

**Comment by bmag-npds** [comment]
@Jireck-npds 
Oui j'ai vu ta proposition, mais comme je me debrouille tres mal sur github, je ne sais plus la retrouver, donc j'ai pas pu tester, mais bien sur l'idée me plait bougrement!
