### ISSUE TITLE
Notice php 

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#162]
Hello Jpb

Voila deux notice que j'ai sur le mainfile 

```
Notice: Undefined variable: affichJ in /var/www/sdb/9/7/jireck/mainfile.php on line 1509

Notice: Undefined variable: affichN in /var/www/sdb/9/7/jireck/mainfile.php on line 1512
```

**Comment by jipexu** [comment]
avec que url ?

**Comment by Jireck-npds** [comment]
celle de base index.php?op=edito

**Comment by jipexu** [comment]
ok

**Comment by jipexu** [comment]
je n'ai pas ce comportement sur le labo (pas de notice) avec la même url ... qu'est ce qui change ? en membre en anonyme ?

**Comment by Jireck-npds** [comment]
Je ne sais pas quel vue j'ai sur votre labo ...

En tout cas, vous avez une chié de notice sur le labo

**Comment by jipexu** [comment]
c'est le module agenda lol

**Comment by jipexu** [comment]
je viens d'en enlever quelques unes ..

**Comment by Jireck-npds** [comment]
A non .... header footer et d'autres

**Comment by jipexu** [comment]
note les notice ...

**Comment by jipexu** [comment]
je suis entrain d'en corriger

**Comment by Jireck-npds** [comment]
Je crois que c'est pas le plus important ...

Je pense qu'il faut finir d'abord le header.php.
Puis ensuite
Faire une grosse passe sur les notices en les listant dans un premier temps puis pour les corriger

**Comment by jipexu** [comment]
vu celle du footer

**Comment by Jireck-npds** [comment]
Notice: Undefined variable: visible_wrn in /home/users/i/infocapagde/www/NPDS/labo/modules/upload/include_forum/upload.func.forum.php(272) : eval()'d code on line 1

http://labo.infocapagde.com/viewtopic.php?topic=798&forum=49

**Comment by Jireck-npds** [comment]
![fichierupload](https://cloud.githubusercontent.com/assets/16939826/26307499/36332590-3ef5-11e7-8806-8cff8b774159.png)
Voila ce que j'ai quand je veux visualiser le fichier joint

**Comment by Jireck-npds** [comment]
Notice: Undefined variable: vs in /var/www/sdb/9/7/jireck/admin.php on line 117

Notice: Undefined offset: -1 in /var/www/sdb/9/7/jireck/admin.php on line 188

Notice: Undefined offset: -1 in /var/www/sdb/9/7/jireck/admin.php on line 188

Notice: Undefined offset: -1 in /var/www/sdb/9/7/jireck/admin.php on line 188
Notice: Undefined variable: Mmembers in /var/www/sdb/9/7/jireck/admin/stories.php on line 76

Notice: Undefined variable: nbg in /var/www/sdb/9/7/jireck/admin/stories.php on line 79

Notice: Undefined variable: Mmembers in /var/www/sdb/9/7/jireck/admin/stories.php on line 76

Notice: Undefined variable: Mmembers in /var/www/sdb/9/7/jireck/admin/stories.php on line 76

Notice: Undefined variable: Mmembers in /var/www/sdb/9/7/jireck/admin/stories.php on line 76
Notice: Undefined variable: hometext in /var/www/sdb/9/7/jireck/admin/stories.php on line 1019
Notice: Undefined variable: bodytext in /var/www/sdb/9/7/jireck/admin/stories.php on line 1027
Notice: Undefined variable: deb_day in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: deb_month in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: deb_year in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: deb_hour in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: deb_min in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: fin_day in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: fin_month in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: fin_year in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: fin_hour in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: fin_min in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031

Notice: Undefined variable: epur in /var/www/sdb/9/7/jireck/admin/stories.php on line 1031
Notice: Undefined variable: short_user in /var/www/sdb/9/7/jireck/mainfile.php on line 2733

Notice: Undefined variable: short_user in /var/www/sdb/9/7/jireck/mainfile.php on line 2733

**Comment by jipexu** [comment]
c'est traité ...
