### ISSUE TITLE
Meta PHP

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#182]
Pas tres correct comme affichage

![meta](https://user-images.githubusercontent.com/16939826/27134674-8874c718-5116-11e7-9a28-a5c3abda3989.GIF)

**Comment by jipexu** [comment]
t'es pas à jour on a plus ça ..recharge le meta de l'admin ... ou github n'est pas à jour ?..

**Comment by Jireck-npds** [comment]
Peux etre ...

Je vais mettre a jour a moins que tu va faire un nouveau package d'ici peu ...

de plus il serait bien de fermer les Issue sur GIT.
Comme tu le sais et je sais tu resolve pas mal de probleme sur le labo de phr et tu met a jour sur GIt (surement) mais comme dis, je n'ais pas acces au labo et je ne peux donc etre au courant si ok ou pas .

Le mieux si tu pouvais faire un nouveau package et une news sur npds pour dire que cela avance cela serait bien ...

**Comment by jipexu** [comment]
j'attend encore un peu 
je pense faire une dernière alpha sous peu (sans les notices) puis une beta quand BS sortira la 4 beta (93% avancement)
