### ISSUE TITLE
Piece jointe non visible en anonyme dans (viewtopic.php)

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#183]
Impossible de visualiser les pieces jointes d'un forum

**Comment by jipexu** [comment]
précise le contexte ... quand elle sont sous quelles forme ?

**Comment by Jireck-npds** [comment]
Je te l'avais déjà fait remarqué, l'icone dans le forum est abscent et l'ouverture de la piece jointe est en raw

**Comment by jipexu** [comment]
comprend pas ... quelle icone? quand tu fais quoi ? quel type de pj ...

**Comment by Jireck-npds** [comment]
Quand tu rajoute un fichier dans un forum, normalement tu as un trombone et quand tu clique dessus cela s'ouvre dans une nouvelle fenetre si c'est une image.

J'ai donc ni le trombone ni le fichier qui s'ouvre correctement

**Comment by jipexu** [comment]
... oui cela fonctionne sur le labo

**Comment by jipexu** [comment]
verifie si tu as bien l'image du trombone car (c a corriger...) elle est en dur du theme npds_boost ...
quand a l'affichage dans l'onglet il devrait être correcte .... ou alors le navigateur n'est pas paramétré pour l'affichage de cette image ??? ou alors t'as des fichiers à la traine ... est ce que le fichier avec son extension est vraiment ce qu'il prétend être ?

**Comment by Jireck-npds** [comment]
Non cela ne fonctionne pas sur votre labo.

**Comment by jipexu** [comment]
si je viens de tester ou alors on parle pas de la meme chose

**Comment by jipexu** [comment]
une url ?

**Comment by Jireck-npds** [comment]
Comme dit j'avais déjà fait la remarque dans https://github.com/npds/npds_dune/issues/162

Cela vient peux etre (pas regarder le code ) de la gestion des droits sur le forum

**Comment by jipexu** [comment]
est ce que tu as essayer avec d'autres fichier (qui auraient un nom plus académique que .... 'Capture d'écran' ...)

**Comment by Jireck-npds** [comment]
Tout les fichiers sont  pareil 
sinon choisi dans le forum de votre portail un fichier dans un forum tu met l'url je te ferais des captures d'ecran

Sinon passe en anonyme sur ton labo

**Comment by jipexu** [comment]
donc en résumé on ne vois pas l'image quand on est en anonyme alors que je la vois quand je suis en tant que membre ....

**Comment by Jireck-npds** [comment]
A verifier si c'est cela ... moi je ne peux pas changer d'anonyme à user et inversement ...
teste et confirme

**Comment by jipexu** [comment]
>donc en résumé on ne vois pas l'image quand on est en anonyme alors que je la vois quand je suis en tant que membre ....

**Comment by jipexu** [comment]
#186 fixé

**Comment by Jireck-npds** [comment]
Il aurait été bien d'avoir la solution ici. autre que sur un labo ou je n'ai pas acces....

De plus dans mon printscreen, il y avait les deux notice problematique....

Donc il y avait tout.
Mais bon, j'ai vu que la confiance en mes reporting etaient mis a rude epreuve..... pour pas dire remis en question. ca donne envie d'aider.
Passons ....

Je suis tres content que tu es trouvé.... merveilleux !!!

**Comment by jipexu** [comment]
tu as la solution ici dans le commit et un bref commentaire ...
tes reporting sont ce qu'ils sont ... avant de les traiter il faut pouvoir les comprendre ! et pour cela il faut qu'il soit le plus précis possible dans le contexte ... particulièrement celui-ci qui était un peu tordu puisque c'est seulement avec le grabglobal au maxi que l'erreur d'affichage (logiquement) se produisait donc au final à cause de l'affichage des 2 notices .... donc voilà

**Comment by Jireck-npds** [comment]
OK
Marchons comme cela
