### ISSUE TITLE
alpha 7

### ISSUE THREAD

**Issue by jipexu** [npds/npds_dune#189]
Dernière alpha
En attente Beta 0 BS 4

**Comment by Jireck-npds** [comment]
Tu peux faire une Beta 0.1 histoire d’être sur que tout est a jour et qu'on puisse tester serein ?

**Comment by jipexu** [comment]
oui dans la semaine je pense faire la dernière alpha pour test (pour voir si y'a pas de grosse bourde) et juste après une première beta ....

**Comment by Jireck-npds** [comment]
OK J'attends la derniere alpha alors...

**Comment by jipexu** [comment]
cool !

**Comment by jipexu** [comment]
alpha 7 dans les bacs

**Comment by Jireck-npds** [comment]
C'est donc la beta 0 plutot que alpha 7 ?
Ou tu fais un changement de nom ?

**Comment by jipexu** [comment]
alpha 7
