### ISSUE TITLE
Contenu du tooltip du Bloc catégories

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#198]
Bonjour,

dans le bloc catégorie, quand on survole une catégorie, il y a une date qui s'affiche.

Il aurait été mieux d'être plus explicite du genre : 
"Dernière mise à jour de la catégorie : 19/07/2017"
ou
"Dernière article publié dans cette catégorie : 19/07/2017"

de plus pour moi, l'heure est facultatif...
Mais je comprends que pour certains sites cela soit nécessaire.

Voila

**Comment by jipexu** [comment]
"Dernière article publié dans cette catégorie : 19/07/2017" (avec l'heure)

celui la est le mieux ...?

**Comment by Jireck-npds** [comment]
Je pense que 
"Dernière mise à jour de la catégorie : 19/07/2017" est mieux...
Apres demande aux gars du labo...

**Comment by jipexu** [comment]
fixed by #361
