### ISSUE TITLE
Mise en page bloc Anciens Articles

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#199]
Bonjour,

Je pense qu'il y a un problème de mise en page (visible sur votre labo).

Les articles a titre court ont l'indicateur qui est sur la même ligne.
Les articles a titre long ont l'indicateur qui est sur la ligne en dessous.

de plus, c'est un indicateur de quoi ? 
Je pense qu'il aurait été bien de mettre un popup en disant : commentaires ou nombre de lecture ou ??

Cordialement

**Comment by jipexu** [comment]
oui ... to do

**Comment by jipexu** [comment]
fait
