### ISSUE TITLE
installation manuelle alpha 7 SQL

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#217]
Lors de l'injection du fichier SQL 

```
Erreur
requête SQL:

INSERT INTO metalang( def, content, type_meta, type_uri, uri, description, obligatoire ) 
VALUES (

'yt_video', 'function MM_yt_video($id_yt_video) {\r\n   $content="";\r\n   $id_yt_video = arg_filter($id_yt_video);\r\n\r\n   $content .=''<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/'.$id_yt_video. '" allowfullscreen="" frameborder="0"></iframe></div>'';\r\n   return ($content);\r\n}',  'meta',  '-',  '',  '[french]Inclusion video YouTube.  Syntaxe : yt_video(ID de la vid&eacute;o).[/french][english]...[/english]',  '1'
);

MySQL a répondu:Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.$id_yt_video.'" allowfullscreen="" frameborder="0"></iframe></div>'';\r\n   ret' at line 1 
```

**Comment by jipexu** [comment]
avec l'install auto ?

**Comment by jipexu** [comment]
peux tu supprimer les double simple quotes qu'il ya ligne 654 du fichier sql ... je pense que ce doit etre la boulette ...ici :
`$content .=''<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/'.$id_yt_video.'" allowfullscreen="" frameborder="0"></iframe></div>''`

et réessayer ?

**Comment by jipexu** [comment]
....non je ne pense pas que ce soit celà .....

**Comment by Jireck-npds** [comment]
Pas chercher mais en supprimant la ligne l’injection fonctionne

**Comment by jipexu** [comment]
faudra chercher car cela signifie que l'on ne peut PAS servir du fichier sql comme tu l'a fait ... et qu'on est obligé d'utiliser l'install auto ...
il faudra donc le réécrire ...

**Comment by Jireck-npds** [comment]
Je pense qu'il faut juste regarder la ligne du meta... cela devrait etre assez facile ...

Pour l'instant, je finis l'upload des fichiers sur le serveur avant d'aller plus loin

**Comment by jipexu** [comment]
''.$id_yt_video.''  ceci doit etre bon ...

`$content .=''<div class="embed-responsive embed-responsive-16by9"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/''.$id_yt_video.''" allowfullscreen="" frameborder="0"></iframe></div>''`

**Comment by jipexu** [comment]
#229
correction
