### ISSUE TITLE
install free.fr

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#220]
Bon avec l'install auto impossible d'installer npds

Version actuelle de PHP : 4.4.3-dev
NPDS nécessite une version 5.3.0 ou supérieure !

c'est la config par defaut de free.

**Comment by Jireck-npds** [comment]
impossible de créer la base de données en remplissant le formulaire

**Comment by jipexu** [comment]
il faut mettre le htaccess de free ...@bmag

**Comment by Jireck-npds** [comment]
Je sais c'est juste qu'il faudrait faire une annexe

**Comment by jipexu** [comment]
>impossible de créer la base de données en remplissant le formulaire

oui la création est désimplémenté ... par contre le remplissage de la base fonctionne (il faut que je change le texte (essaiera de créer la base de donnée car il est faux)

**Comment by Jireck-npds** [comment]
J'ai créer a la main la base.

sur l'index j'ai

`Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/sdb/9/7/jireck/modules/meta-lang/adv-meta_lang.php on line 209
`

**Comment by jipexu** [comment]
sur quoi sur un php 4 ? ca ne passera pas

**Comment by Jireck-npds** [comment]
PHP 5.8

**Comment by Jireck-npds** [comment]
Free avec un htaccess

**Comment by jipexu** [comment]
en 5.6.8 normalement on a pas cette erreur de mémoire ...sur quelle page ?

**Comment by Jireck-npds** [comment]
http://jireck.free.fr

**Comment by jipexu** [comment]
la table metalang doit etre en vrac !

**Comment by Jireck-npds** [comment]
Pour moi elle est correct

**Comment by Jireck-npds** [comment]
Reimporter le fichier sql ==> pareil

**Comment by jipexu** [comment]
est ce que les fichiers mainfile, advmetalang et theme.php dans theme dynamique sont corrects (bien chargé?)

**Comment by jipexu** [comment]
l'erreur est tres haute ...et le moteur metalang ne fonctionne pas

**Comment by Jireck-npds** [comment]
Oui y'a bien les fichiers

**Comment by jipexu** [comment]
c'est soit la table soit un de ces trois fichiers car en principe une 5.6.8 de chez free fonctionne....

**Comment by Jireck-npds** [comment]
Faudrait voir avec un truc complet..
Là J'ai lancer l'install auto et creer la base a la main car pas de creation auto ...

de plus en passant par la creation de la base a la main et la config manuel du fichier config cela ne fonctionne pas

**Comment by jipexu** [comment]
a partir du moment ou tu as ton fichier htaccess (pour ton php 5.6.8)
création de la base à la main
puis install auto ...

**Comment by Jireck-npds** [comment]
tu ne peux pas finir l'install auto puisqu'il peux pas passer la phase de création de la bdd

**Comment by Jireck-npds** [comment]
c'est bien cela je viens de retester
la phase de création de la bdd ==> 
La base de données n'a pas pu être créée. Vérifiez les paramètres ainsi que vos fichiers, puis réessayez à nouveau.
et on ne peux pas passer cette phase

**Comment by jipexu** [comment]
donc ici soit tes paramètres sont faux ... soit l'archive sql n'est pas correcte
La base de données n'a pas pu être créée. <= le script n'essaie meme pas de la créer (faudra changer la formulation)  c'est soit tu n'a pas les droit pour la création des tables soit l'archive est corrompu ou ton fichier conf ?...

**Comment by Jireck-npds** [comment]
C'est correct maintenant en repassant via l'install auto donc surement en revalidant un parametre dans le fichier config... j'en sais rien c'est vraiment bizarre mais  disons que si l'install auto ne peux pas creer la base ... ??

**Comment by jipexu** [comment]
fixed ? #231 

en fait (très curieusement==> il devrait pourtant !) cette configuration de free ne propose pas l'extension mysqli (que nous avions automatisé dans l'install en fonction de la version...)

**Comment by Jireck-npds** [comment]
Mysqli est disponible chez free en version 5.6.8
http://jireck.free.fr/phpinfo.php

**Comment by jipexu** [comment]
pas sur le serveur sql !?

**Comment by jipexu** [comment]
![extension mysql](https://user-images.githubusercontent.com/328101/29616201-027980b8-8811-11e7-93a9-9d62a0cb4894.jpeg)

**Comment by jipexu** [comment]
?? tu as la meme chose ?

**Comment by Jireck-npds** [comment]
je check

**Comment by Jireck-npds** [comment]
deja dans mon config.php 
$mysql_i = 1

**Comment by jipexu** [comment]
regarde la modif dans lib que j'ai faite et change le conf (par default dans l'archive il est a mysql ...)

**Comment by jipexu** [comment]
solved
