### ISSUE TITLE
Question | Admblock

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#221]
Cette table va contenir une ligne ??
J'ai pas chercher juste lu la table ...

**Comment by jipexu** [comment]
pour l'instant rien de changé ... c'est la même qu'avant ...

**Comment by Jireck-npds** [comment]
oki je m'en rappelais pas ...

donc cette table ne sert a rien ... mais ... historiquement on laisse pour l'instant

**Comment by jipexu** [comment]
oui on pourrait peut être s'en passer en réimplémentant autrement ...

**Comment by Jireck-npds** [comment]
A laisser comme cela alors et à mettre dans les reflexions pour un patch ou prochaine version

**Comment by jipexu** [comment]
oui je vais le mettre dans une roadmap (projet) d'amélioraton code ....

**Comment by nicolas2** [comment]
admblock et mainblock sont a fusionner ajouter un id champ et faire un select sur id. supprime une table sql pas utile

**Comment by jipexu** [comment]
Oui c'est toujours dans les suggestion d'amélioration de code....  PR bienvenue ! ...

**Comment by nicolas2** [comment]
voir pull https://github.com/npds/npds_dune/pull/503

**Comment by nicolas2** [comment]
suite erreur de ma part sur pull request sur #503 mise a jour pour merge 
https://github.com/npds/npds_dune/pull/504

**Comment by jipexu** [comment]
merci @nicolas2  @Jireck-npds 
closed with #504
