### ISSUE TITLE
Preference

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#223]
Bonjour,

c'est bizarre qu'il y est toujours "**Polices du site**" dans les préférences 

c'est pas la css qui décide ...?

**Comment by Jireck-npds** [comment]
Obligation de mettre un mail dans : 
Compte E-mail (Provenance)
Alors que je met : 
Non dans Notifier les nouvelles contributions par E-mail
et
que le champs a la base est vide

**Comment by jipexu** [comment]
>Bonjour,
c'est bizarre qu'il y est toujours "Polices du site" dans les préférences
c'est pas la css qui décide ...?

oui ca ne sert plus à rien ..... c'est a désimplémenter ...

**Comment by jipexu** [comment]
>Obligation de mettre un mail dans :
Compte E-mail (Provenance)
Alors que je met :
Non dans Notifier les nouvelles contributions par E-mail
et
que le champs a la base est vide

c'est parce que c'est utilisé (la variable) ailleurs (de mémoire download ou link ...)

**Comment by Jireck-npds** [comment]
A remplir par defaut avec la meme chose qu'au dessus 
webmaster@site.fr ou quelque chose comme cela ...
