### ISSUE TITLE
Top

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#224]
Bonjour,

Quelques remarques sur la pages Top.php
- le titre "Bienvenue sur la page de garde de "
je prefere, a voir avec d'autres : 
Bienvenue sur la page de **recapitulative** de
Bienvenue sur les **Statistiques du site** de
Page de garde, ca fait comme dans un livre premiere page a lire etc ...
- avant les titres il ne vaudrait pas mettre "**Les**"
- il serait bien de mettre un truc quand il n'y a rien : 
0 ou le mieux c'est de ne pas afficher la rebrique si le retour est vide.
Exemple : je désactive les critiques chez moi et j'ai un encart avec : 
20 Critiques les plus lues
l'affichage si le retour est autre que 0 est le mieux

**Comment by jipexu** [comment]
vrai le titre est nul lol ...
alors 0 ou pas d'affichage quand c'est vide ??

**Comment by Jireck-npds** [comment]
pas d'affichage c'est bien mieux
Comme cela, ce que les gens ne se servent pas ne sera pas visible.

**Comment by Jireck-npds** [comment]
désolé mauvaise fin d'explication sur ma premiere remarque / post

**Comment by jipexu** [comment]
j'ai regardé ta proposition
> pas d'affichage quand c'est vide 

l'ennui c'est que c'est extrêmement compliqué à implémenter ... à cause du contexte metamot + template  html .....  (sans refaire tout les meta top pour y inclure les titres et la structure html auquel cas le template ne servirai plus à grand chose ....) à moins que tu es une solution miracle ?? ou alors j'ai loupé quelque chose ...

@ suivre

**Comment by Jireck-npds** [comment]
Je n'avais pas regardé l’implémentation.
Apres regarde cela me semble effectivement compliqué.
Restons simple, ajoutons juste un message dans les fonctions de retour de top du genre : 
```
if (nombre de ligne = 0 and $admin)
      echo 'pas de ligne, si c'est une option de npds que vous n'utilisez pas vous pouvez la supprimer en editant le fichier top.html de votre theme';
```
