### ISSUE TITLE
topicsmanager

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#225]
Y'a un problème de mise en page 

la suppression est en bas a droits et la modification juste sous l'image et je comprends pas le popup avec l'id.

Voila ce que j'aurais vu : 
1) 2 sujets par ligne; le cadre global d'un sujet devient trop grand sans information
2) regroupement de l'edition et la suppression en bas a droite
3) ajout d'un oeil pour voir le visuel index.php?op=newtopic&topic=X
4) donner d'autres infos sur le popup genre nombre d'article lié ou autres (a definir)

Voila
c'est ma vision / avis

**Comment by jipexu** [comment]
revu
