### ISSUE TITLE
ephemeride

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#226]
Il serait pas mal de mettre au moins une entrée dans la base ainsi que la possibilité de lister tous les ephem.

**Comment by jipexu** [comment]
pourquoi une entrées (personne ne la verrait...)

>> la possibilité de lister tous les ephem.

dans l'admin ? en user ?

**Comment by Jireck-npds** [comment]
Une entré permet de voir au moins en admin comment cela se passe...

outre ephemeride il est toujours bien d'avoir au moins une / + entree dans une fonction afin de voir ce que c'est
