### ISSUE TITLE
Newtopic

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#227]
Je pense qu'il serait mieux de mettre  : 
col-sm-2 col-sm-10
plutot que 
col-sm-3 col-sm-9

Cela fait plus equilibré, il me semble

**Comment by jipexu** [comment]
oui mais ca ne passe pas (plus) ... sur les themes a 3 colonnes je pense qu'ultérieurement pour ces cas de figure je vais utiliser flex plutot que la grille ce sera parfait pour ce genre de cas ....

**Comment by Jireck-npds** [comment]
Je vais tester a moins que tu l'ai fait sur 3 colonnes...
Flex sera mieux ...sur !

**Comment by jipexu** [comment]
tout sur une colonne ...
