### ISSUE TITLE
New NPDS

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#230]
Hello Jpb,
Ca serait bien que tu fasse un news sur npds pour dire de tester la derniere alpha...
Et de poster les troubles sur futurs version.

La date de la derniere news npds date de decembre je crois

Issue a close ensuite

**Comment by jipexu** [comment]
ouip il faudra ....  si tu as des idées ?
pour début septembre ...
je laisse ouvert pour le faire !

**Comment by Jireck-npds** [comment]
Je pense qu'il faut rester simple du genre : 

> Bonjour,
> Voici des nouvelles de npds.
> Apres 1 année de développement, nous venons de sortir une alpha test (la N°7) et nous aimerions avoir vos tests et avis.
> Pour télécharger cette version, [lien vers Git ] et merci de poster vos retour soit sur git => issue ou sur le forum futur version.
> 
> Les principaux axes d’amélioration sont : responsive, normalisation, évolution afin de répondre au moins aux pratiques du web.
> merci 
> NPDS Team

**Comment by jipexu** [comment]
==> fait
