### ISSUE TITLE
amélioration mise en page autodoc

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#232]
Il il a un probleme de mise en page avec l'aide des blocs

autodoc.php?op=blocs

**Comment by jipexu** [comment]
lequel ? probleme ?

**Comment by Jireck-npds** [comment]
Y'a un probleme de colonne regarde tu verra tout de suite

**Comment by jipexu** [comment]
oui vu c'est pas simple lol car la mise en page est faite dans les fichier ou se trouve les fonctions je vais amélioré ça .....

**Comment by jipexu** [comment]
fixed #233
