### ISSUE TITLE
notice à la génération de sitemap en admin

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#237]
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/sdb/9/7/jireck/sitemap.php on line 134

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/sdb/9/7/jireck/sitemap.php on line 137

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/sdb/9/7/jireck/sitemap.php on line 140

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/sdb/9/7/jireck/sitemap.php on line 143

Warning: Variable passed to each() is not an array or object in /var/www/sdb/9/7/jireck/sitemap.php on line 111

**Comment by jipexu** [comment]
oui ! 
on a cette erreur depuis Rev13 et le nouveau sitemap.php ....
en fait c'est probablement une incompatibilité entre sitemap.php et pages.php dans lequel l'admin n'a pas de référencement pour sitemap ...!??  je me suis pas encore vraiment penché dessus car pour la voir il faut être dans l'admin Quand le sitemap se regénère me semble t il donc délicat à debugger ..... si tu observe mieux le contexte ...
