### ISSUE TITLE
Question editeur

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#239]
Hello 

Comment fait tu pour initialiser l'editeur dans un formulaire dans l'admin d'un module ? 

J'ai 
`    $PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxxxx&ModStart=admin/admin*']['title']=""; 
    $PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxx&ModStart=admin/admin*']['run']="yes"; 
    $PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxxx&ModStart=admin/admin*']['blocs']="0"; 
    $PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxxx&ModStart=admin/admin*']['TinyMce']=1; 
    $PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxxx&ModStart=admin/admin*']['TinyMce-theme']="full"; `

et dans ma page 
`	.'<textarea class="form-control tin" wrap="virtual" cols="55" rows="10" name="pres" id="pres"></textarea>';
	echo aff_editeur("pres", "true");
`

Merci pour tes futurs informations

**Comment by jipexu** [comment]
ceci nous ramène probablement au sujet de discussion que nous avions eu sur la faiblesse de pages.php ...

à quoi sert wrap virtuel dans ce cas là ?..?

as tu tiny chargé pour admin.php ? charge le pour controler ...
$PAGES['admin.php']['TinyMce']=1;
$PAGES['admin.php']['TinyMce-theme']="full";

comme exemple il ne me semble pas que l'on est un tiny dans l'admin d'un des modules ... je vais regardé par contre dans la partie "user" des modules ça fonctionne ...

**Comment by Jireck-npds** [comment]
dans la partie user des modules ca fonctionne.

```
// admin why charge the tiny on each admin page 360k !! ??
$PAGES['admin.php']['title']=""; // obligatoirement à vide
$PAGES['admin.php']['blocs']="0";
$PAGES['admin.php']['run']="yes";
$PAGES['admin.php']['TinyMce']=1;
$PAGES['admin.php']['TinyMce-theme']="full";
$PAGES['admin.php']['css']=array("admin.css+",$nuke_url."lib/bootstrap-colorpicker-master/dist/css/bootstrap-colorpicker.min.css+");
$PAGES['admin.php']['TinyMceRelurl']="false";
```
J'ai ca par defaut 
Maintenant je n'ai pas vérifier ce que tu as fait au niveau du chargement de tiny dans le header
Dans submit.php c'est OK 
dans le module coté user c'est OK

**Comment by Jireck-npds** [comment]
pour le wrap c'est que j'ai par encore epuré mon cote pour passer a BS

**Comment by Jireck-npds** [comment]
> ceci nous ramène probablement au sujet de discussion que nous avions eu sur la faiblesse de pages.php ...

Je ne retrouve notre discution sur le sujet .... et surtout la solution que je t'avais proposer et qui pour moi etait bonne .... 
Tu avais modifier le header.php ou pas ...

**Comment by Jireck-npds** [comment]
Tu as des news ? 
Tu aurais un lien pour la discution sur le chargement de tinymc je ne le trouve plus en cherchant longtemps ...
Je pense que ma solution était bonne, mais si elle ne te convenait pas j'aimerais la reprendre.
Merci jpb

**Comment by Jireck-npds** [comment]
si je rajoute : 
`$tmp="
      <script type=\"text/javascript\">
      //<![CDATA[
      $(document).ready(function() {
         tinymce.init({
            selector: 'textarea.tin',
            height: 300,
            theme : 'modern',
            language : '".language_iso(1,'','')."',";
               include ("editeur/tinymce/themes/advanced/npds.conf.php");
               $tmp.='
            });
         });
      //]]>
      </script>';`

Dans mon fichier, j'ai l'editeur ...
la lib tiny est bien initialisé mais pas lancé ...

**Comment by jipexu** [comment]
si tu ne met rien dans le page.php de ton module (donc tu t'appui sur le chargement de tiny par defaut de l'admin avec le page.php racine) alors cela doit fonctionner
je viens de faire l'essai dans l'admin de glossaire et ca fonctionne

**Comment by Jireck-npds** [comment]
Toujours pas ...

Alors je resume : 

Plus de declaration dans le pages.php du module.

dans la source de l'admin du module 
La lib est bien inclue dans le header
`<script type="text/javascript" src="editeur/tinymce/tinymce.min.js"></script>`

Et je déclare ca dans le code (je fais peux etre une erreur : 
`	echo '<textarea class="tin" cols="55" rows="10" name="Npres">'.$pres.'</textarea>';
	echo aff_editeur('Npres', '');`

**Comment by jipexu** [comment]
non ta déclaration dans le code à l'air correcte ... dans l'essai que j'ai fait sur glossaire il y a les deux (...) pages.php le racine et celui du module et ca fonctionne ...

**Comment by jipexu** [comment]
c'est sur ton labo en ligne  ?

**Comment by Jireck-npds** [comment]
Oui c'est en ligne 
Je n'ai tester que sur chrome mais le submit fonctionne

dans $pres, il n'y a que du texte sans rien de plus là j'ai mis la version qui mofifie $pres mais dans un autre formulaire il n'y a rien et je fais la même declaration
`echo '<textarea class="tin" cols="55" rows="10" name="pres"></textarea>';
	echo aff_editeur('pres', '');`

ca c'est pour ecrire une presentation, le premier pour la modifier...

Si je rajoute Comme dit : 
```
$tmp=" <script type=\"text/javascript\"> //<![CDATA[ $(document).ready(function() { tinymce.init({ selector: 'textarea.tin', height: 300, theme : 'modern', language : '".language_iso(1,'','')."',"; include ("editeur/tinymce/themes/advanced/npds.conf.php"); $tmp.=' }); }); //]]> </script>';
echo $tmp;
```

L'editeur fonctionne mais c'est qu'un paliatif

**Comment by jipexu** [comment]
je pense que c'est parce ce que tu n'a pas inclu le footer.php dans ce context sans le footer ca ne peut pas fonctionner ...

**Comment by Jireck-npds** [comment]
Ca a changer alors car normalement c'est le admin.php de NPDS qui se changeait de charger header et footer....

Il faut charger quel footer ?

**Comment by Jireck-npds** [comment]
Je viens de regarder le module....

cela fait "Bizarreé (anormal) de devoir mettre un footer sans header et que cela ne soit pas gerer par le admin de npds.

de plus dans le code on a : 
`   echo '</div>';
   include ("footer.php");`

Et donc ni header.php
ni ouverture de div dans le fichier

**Comment by jipexu** [comment]
>Ca a changer alors car normalement c'est le admin.php de NPDS qui se changeait de charger header et footer....

oui  c'est toujours le cas il faut juste utiliser les fonctions de l'admin (et si tu n'utilise pas ces fonctions tu peux faire une inclusion simple du footer.php

pour le header de l'admin c'est pareil c'est elle qui ouvre le dive d-te permettant d'inclure tous dans l'admin (et la fonction adminfoot ferme le div)

**Comment by Jireck-npds** [comment]
C'est bizarre quand meme
De plus comme je le disais dans les autres versions **pour moi** si on a un fichier footer inclue il faut un fichier header.
Si un div est ouvert / fermer ou autre balise, il faut que cela soit fait dans le code et non dans une fonction.

d'apres ce que tu m'explique, je me trompe peut etre. 
Tous les fichiers inclues par l'admin (tous ceux dans le repertoire admin) sont gerer automatiquement par le fichier admin (header / footer) sauf pour les modules alors que cela devrait etre fait afin d'evité les inclusions bizarre comme je dis ....
surtout que généralement les gens se basent sur les fichiers existants.

Ne serait pas plus simple de le mettre dans le fichier plugins.php ?????

**Comment by jipexu** [comment]
non c'est juste qu'il faut utiliser les fonctions de l'admin c'est tout .. meme pour les modules comme ça tu bénéficie de tous ce que ca peut t'apporter dans le header fichier d'aide de l'admin du module, interface et dans le footer validation des form, div fermante et inclusion du footer ou pas suivant les paramètres ...

**Comment by jipexu** [comment]
typiquement dans un fichier d'admin de modules
....

//==> controle droit
admindroits($aid,$f_meta_nom);
//<== controle droit
   GraphicAdmin($hlpfile);
   adminhead ($f_meta_nom, $f_titre, $adminimg);
............blala bla bla.......
adminfoot('','','','');

**Comment by Jireck-npds** [comment]
Alors reponse a tes arguments  ne repondant pas a ma question: 
Je reformule mes interrogations et etonnements a tes reponses.

Question de ton code et je ne sais pas ce que fais ces fonctions / ou presque.
admindroits($aid,$f_meta_nom); ==> OK Je trouve cela tres bien 
GraphicAdmin($hlpfile); ne sert a rien pour moi dans les modules
adminhead ($f_meta_nom, $f_titre, $adminimg); Formate un header qui deforme mes modules et ne reponds a rien a par normaliser un module qui est par definition different.
donc pour moi pas obligatoire, et il a l'air non obligatoire.

adminfoot('','','',''); Je ne sais pas a quoi il sert ? 
a inserer un footer ?
a ajouter un controle de formulaire ? (si c'est cela va falloir expliquer le fonctionnement)
div fermante qui est ouvert ou ? il faut decoreler le code du html...

Donc adminfooter prends 4 parametres .... et a l'air de faire le café mais par defaut on l'appel sans parametres... bizarre ...

De plus pour revenir a mon probleme de footer .
Pourquoi inclure le footer si c'est juste pour avoir un End_tinymce ?
pourquoi ne pas mettre la fin de tinymce dans plugin ? 
Pourquoi ne pas exploser la fonctione adminfoot si elle fait trop de chose afin de pouvoir sortir le html du code.

**Comment by jipexu** [comment]
ce que je t'ai exposé permet  juste 
d'avoir une interface générale et fonctions disponible pour les modules similaire à celle de l'admin ...
libre à toi de l'utilisé ou pas ...
GraphicAdmin($hlpfile); ne sert a rien pour moi dans les modules ==> utiliser l'interface d'affichage du fichier d'aide si il existe

adminhead ($f_meta_nom, $f_titre, $adminimg); Formate un header qui deforme mes modules et ne reponds a rien a par normaliser un module qui est par definition different.
donc pour moi pas obligatoire, et il a l'air non obligatoire.
==> non pas obligatoire (si il déforme ton admin c'est justement parce que tu ne ferme pas avec adminfoot)

adminfoot('','','',''); Je ne sais pas a quoi il sert ?
==> lis la fonction dans le mainfile ....

pour résumé cette architecture est exactement la meme que celle qu'on utilise dans l'architecture du portail (header.php/contenu/footer.php)au lieu que ce soit des inclusion de fichier ce sont des fonctions c'est tout ....

Pourquoi inclure le footer si c'est juste pour avoir un End_tinymce ? 
==> (pour entre autre permette que tiny charge quand page.php ne le fait pas ....)
==> pour inclure tes footer html et conserver la meme présentation sur tout le portail

donc tu peux ou pas utiliser pour intégrer ou pas ton admin dans l'interface générale de l'admin (c'est tout ...)

**Comment by Jireck-npds** [comment]
Merci pour les explication Jp
Je vais lire adminfoot et te faire un retour ...

Quand même bizarre que dans mon module (qui marche), on soit obliger d'inclure le footer.php pour afficher l'editeur alors que j'ai un pages.php.
C'est comme cela qu'on avait defini le truc au niveau des themes et des modules. on disait : 
mettez un pages.php inclu et le core npds gere le reste header footer chargement de tinymce et certaines fonctions de mise en page + la secu "general"

Je vais tout regarder les fonctions que tu me donne. et je reviens vers toi 

ca te conviens ? je discute beaucoup la dessus pas parce que cela change, c'est pour facilité le developpement de module par un tiers.

**Comment by jipexu** [comment]
oui justement la c'est plus facile pour quelqu'un qui ne sait pas trop (pour la gestion des droits et l'inclusion de l'admin du module dans l'interface de l'admin) il faudra le documenter 

>Quand même bizarre que dans mon module (qui marche), on soit obliger d'inclure le footer.php pour afficher l'editeur alors que j'ai un pages.php.

comme on l'a dit c'est toujours notre problème de pages.php et sa limite actuelle ...

**Comment by Jireck-npds** [comment]
Je croyais que tu avais pris ma modif du header qui corrige cela ...

**Comment by jipexu** [comment]
non toujours pas implémé

**Comment by Jireck-npds** [comment]
Cela serait bien .... 
C'est pas définitif ... il y a surement des lacunes mais je pense que le mettre en place réglerais : 
le chargement constant dans l'admin) 
la problème actuel ?

**Comment by Jireck-npds** [comment]
Je viens de regarder le global header / admin / footer

Je reste donc sur mon avis.

Je pense que l'admin doit charger le header et le footer.
Je pense que tu devrais sortir le include footer de la fonction adminfoot.

Comme cela dans le cadre de la compréhension, on verrais les include header / footer qui sont distinct des fonctions de vérification des formulaires et de la mise en page header etc ...

Le rajout de footer dans plugin 

la séquence serait alors normé comme dans les fonctions admin de base

Pour les modules le header.php et footer.php encadre le tout.

//==> controle droit **OBLIGATOIRE**
admindroits($aid,$f_meta_nom);
//<== controle droit
GraphicAdmin($hlpfile); ==> Si vous avez des aides au modules (**OPTIONNEL**)
adminhead ($f_meta_nom, $f_titre, $adminimg); (MISE EN FORME " grandement préconisé( fonctionne avec adminfoot) **OPTIONNEL**)
............ L'ADMIN DU MODULE
adminfoot('','','',''); (MISE EN FORME grandement préconisé ( fonctionne avec adminhead) **OPTIONNEL**) Assure le controle des formulaires

Avantage de la solution proposé : 
Code plus comprehesible
Gestion de pages.php ==> OK sous reserve de la modification à perfectionner
Liaison des deux fonctions (adminfoot et adminhead) car balise ouverte dans l'une et fermer dans l'autre.

Inconvénients : 
A toi de me dire  !?!

Qu'en pense tu ?

**Comment by Jireck-npds** [comment]
un avis ?

**Comment by Jireck-npds** [comment]
???

**Comment by jipexu** [comment]
oui ..
je ne vais pas remodifier tous les fichier admin ... donc je laisse la même architecture qui fonctionne très bien ...
que ces fonctions soient à dispo pour les modules ne constitue pas une obligation ...(c'est juste la solution pour une intégration de l'admin d'un module dans l'interface générale)
comme je te l'ai indiqué tu es libre ou pas d'utiliser les fonctions  pour l'admin de ton module et tu peux très bien utiliser une fonction sans l'autre (en paramétrant adminfoot et donc aussi ton html) ...

exemple : tu peux très bien NE PAS intégrer l'admin de ton module mais utiliser quand meme le contrôle de formulaire 

include header.php
ton code admin de module
adminfoot('fv','','','false');
include  footer.php
---------
et concernant pages.php j'ai fait quelques essais (plus ou moins fructueux)  mais toujours en stanby jusqu'au prochain essai
---------

et pour revenir sur tiny qui ne chargeait pas tu avais bien un include du pages.php de ton module ? ou c''était dans le pages.php racine ? car avoir un pages.php dans un module ne sert à rien car aucune fonction ne le charge (contrairement au pages.php du thème....) il faut donc le charger dans le code du module pour que ca fonctionne ....

**Comment by Jireck-npds** [comment]
Exact pour le controle formulaire ... je voyais exactement comme cela mais comme c'etait a l'origine le footer include c'etait pas top là l'architecture est respecter avec un header et un footer et tes fonctions qui normalise et aide dans les formulaire en autres ...

Concernant le pages.php, ilfaudrait que tu me donne tes essaies; mais je pense que le probleme ne vient pas dans le code mais dans la facon d'utiliser pages.php.

Quand je t'ai donné mon code, j'ai donné en meme temps la facon de l'utiliser. 
oui la facon est pas idéal mais cela fonctionnait a moins que tu es un exemple de non fonctionnement .

de ce que je me souviens, on etait obliger de declarer les pages de l'admin utilisant l'editeur, il n'y en a pas tant que cela surtout si on met cela dans le pages (racine) et qu'on ne fait que surchargé les pages de theme. je ne retrouve plus ma suggestion car il etait sur une modif ... si tu as l'url je suis preneur je checkerais un soluce ...

Question du pages.php dans les modules, cela fonctionne tres bien pour moi ...
autant pour les pages commencant par modules.php que par les pages admin.php?extend....

Dans mon admin j'ai un standard : 
```
	if (file_exists('modules/'.$ModPath.'/admin/pages.php'))
	{
		include ('modules/'.$ModPath.'/admin/pages.php');
	}
```
Avec dans les pages : 
```
	$PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxx&ModStart=admin/admin*']['title']="";
	$PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxx&ModStart=admin/admin*']['run']="yes";
	$PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxx&ModStart=admin/admin*']['blocs']="0";
	$PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxxxx&ModStart=admin/admin*']['TinyMce']=1;
	$PAGES['admin.php?op=Extend-Admin-SubModule&ModPath=xxx&ModStart=admin/admin*']['TinyMce-theme']="full";
```
J'ai un peu de temps et si tu veux de l'aide pour des trucs il suffit de logger un issue et je te fais des rapports...
Si tu as envie ..

**Comment by jipexu** [comment]
je  n'ai pas retrouvé où tu as fait le commentaire et pourtant j'ai cherché .... ne serait ce pas dans ton fork ?

**Comment by Jireck-npds** [comment]
Je viens de passer 1 Heure a rechercher le post et rien.

Le principe (on parle de l'admin.php) étant de faire comme cela : 

On utilise ce qui est déjà fait avant c'est a dire de prendre pour l'admin le premier argument de l'url 
Exemple : admin.php?op=Edito_load, etc ...
Et de checker dans le fichier pages.php s'il y a la ligne et si oui on fait ce que dit pages.

Cela permettrait de :  

- Supprimer le chargement de l'editeur dans l'url de base admin.php.
- Pouvoir charger des JS et CSS specifiquement a certaines pages admin. exemple colorpicker, datepicker, etc ...
- Charger uniquement tinyMCE quand il le faut.

On utilise pour cela le pages à la racine pour fixer le chargement correct de l'admin et on surcharge pages.php avec ceux dans le theme ou dans le module.

Je reviens aussi sur la structure JS CSS qui me semble mieux  : 
les css et js du genre :

lib / css
lib / css / bootstrap
lib / css / bootstrap / table
lib / css / bootstrap / datepicker
lib / css / bootstrap / hightlight
lib / css / jquery
lib / css / jquery / plugin_x

et la même pour les js.
lib / js
lib / js / bootstrap
lib / js / bootstrap / table
...

**Comment by Jireck-npds** [comment]
J'ai oublié : 
Il faut encadré les url admin avec les bons chargements avec un warning precisant qu'il faut ses lignes pour que l'editeur marche dans l'admin.

**Comment by Jireck-npds** [comment]
Donc le sujet est mort ou pas ?
