### ISSUE TITLE
Probleme Editeur

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#241]
Lorsque l'editeur est lance le nom police est pas inscrit
![capture](https://user-images.githubusercontent.com/16939826/30420537-2319526e-993a-11e7-8bf4-e47e004ad61f.GIF)

**Comment by Jireck-npds** [comment]
Une info ?

**Comment by jipexu** [comment]
non je ne sais pas si c'est normal (tint comportement) ou pas (notre implémentation)  faut que je regarde tiny ...

**Comment by Jireck-npds** [comment]
Ok et pour l'autre sujet

**Comment by jipexu** [comment]
#380
