### ISSUE TITLE
Discution header.php | 

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#247]
Hello JPB,

J'ouvre cet issue que tu peux requalifier afin de definir le process header au niveau de pages.

Ne devrait on pas revoir le cycle de contrôle du genre (commence ligne 171) : 

faire un switch case a partir de la ligne 185 avec un truc dans le genre 

```
switch ($pages_ref){

case "static.php" :
      $pages_ref=substr($REQUEST_URI,strpos($REQUEST_URI,"static.php"));
   break;

case "modules.php" :
      if (isset($PAGES["modules.php?ModPath=$ModPath&ModStart=$ModStart*"]['title'])) {
         $pages_ref="modules.php?ModPath=$ModPath&ModStart=$ModStart*";
      } else
         $pages_ref=substr($REQUEST_URI,strpos($REQUEST_URI,"modules.php"));

   break;

case "admin.php" :
      if (array_key_exists(1,$page_uri)) {
         if (array_key_exists($pages_ref."?".$page_uri[1],$PAGES)) {
           // Si un argunment existe dans pages c'est que l'url a traiter est celle avec les arguments
               $pages_ref.="?".$page_uri[1];
         }
      } 
break;

default:
// Pas de modif de  $pages_ref
break;

   // -----------------------
   // A partir de ce niveau - $PAGES[$pages_ref] doit exister - sinon c'est que la page n'est pas dans pages.php
   // -----------------------
// on check si cela doit tourné sinon pas la peine d'aller plus loin
if ($PAGES[$pages_ref]['run']=="no") {
... ORIGINE
}
Run autre pages ... 

Gestion des titres

Gestion tinyMce
 // Initialisation de TinyMce
// Partie a revoir suivant nos discutions sur l'initialisation 
   global $tiny_mce,$tiny_mce_theme,$tiny_mce_relurl;
   if ($tiny_mce) {
      if (array_key_exists($pages_ref,$PAGES)) {
         if (array_key_exists('TinyMce',$PAGES[$pages_ref])) {
            $tiny_mce_init=true;
            if (array_key_exists('TinyMce-theme',$PAGES[$pages_ref]))
               $tiny_mce_theme=$PAGES[$pages_ref]['TinyMce-theme'];
            if (array_key_exists('TinyMceRelurl',$PAGES[$pages_ref]))
               $tiny_mce_relurl=$PAGES[$pages_ref]['TinyMceRelurl'];
         } else {
            $tiny_mce_init=false;
            $tiny_mce=false;
         }
      } else {
         $tiny_mce_init=false;
         $tiny_mce=false;
      }
   } else {
      $tiny_mce_init=false;
   }

  // Chargeur de CSS via PAGES.PHP
Celui d'origine mais étant régis par le $pages_ref modifié ou non 
 // Mod by Jireck - Chargeur de JS via PAGES.PHP
Celui d'origine mais étant régis par le $pages_ref modifié ou non 

```
Et là, je pense que le header sera bon 

Apres lecture, vois si tu veux qu'on revois le truc ou pas ... 
Dans tous les cas, ton avis et explications, envies et autres sont les bienvenus.

**Comment by Jireck-npds** [comment]
A jeter un oeil distrait ?

**Comment by jipexu** [comment]
je regarderai ...

**Comment by Jireck-npds** [comment]
Le but etant d'en discuter et de trouver la meilleur solution.

Dans le processus, et comme avait été concu pages.php (et le header), le but premier étant de checker l'url des pages afin de pouvoir moduler les differents parametres npds comme le titre la css; puis par la suite les js et le run etc...

Dan le process normal : il faut donc bien geré le traitement des  url pour ensuite parfaitment traité ensuite le chargement correct du reste des parametres.

la gestion via le switch va permettre de rentré dans tous les cas ( et sous-cas) et ainsi pouvoir gerer l’intégralité des url.

pages / header gérera correctement le chargement des titres / du run / des css / des JS.
 
le process et donc comme cela pour moi hors complement bien sur 

- Check URL
- Traitement url / parametre url si besoin
- Referencement à pages.php
- traitement run redirect ou pas 
- traitement titre 
- traitement CSS
- Traitement JS

**Comment by Jireck-npds** [comment]
Je pourrais te faire un proto mais je ne vois pas comment te le soumettre
