### ISSUE TITLE
Question Jpb

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#255]
Salut JPB,

Je vois que tu prépare une Béta, et je tiens a te féliciter pour le travail accompli.

Il serait bien de mettre a jour tous les issues pour savoir ce qui sont résolu / Futur version / a finir avant release / etc ...

Bravo pour ces 1800 commit et ce travail enorme.

Jireck

**Comment by jipexu** [comment]
la beta 0 est sorti oui j'essaie de continuer de mettre à jour les issues (j'en ai décallé pas mal) pour la beta1 si on peut car il va falloir commencer a se pencher sur un script de migration :-(

et il faut aussi que je fasse une new sur npds ...

**Comment by Jireck-npds** [comment]
Si je peux me permettre, il faut boucler l’énorme travail que tu as fait.
Il faut, pour moi : 
- planifier Les points a fixer pour la beta 1.
- Planifier Les points pour les TODO qui semble un peu long a faire (je mettrais le pages et header la dedans, etc ..)
- Faire une news sur NPDS avec un lien direct sur la Beta 0 ou mettre l'archive sur NPDS et demande de faire les rapport de bug sur futurs version.
- Planifier les script de migration
voila
