### ISSUE TITLE
 forum avec formulaire pour un groupe

### ISSUE THREAD

**Issue by previnfo** [npds/npds_dune#257]
Dans le cadre d'un futur Projet d'amélioration : 
Un groupe doit pouvoir bénéficier d'un forum avec formulaire en développant plus judicieusement la table SQL pour une meilleure répartition des variables (types de forum). En effet, actuellement "$forum_pass" concentre en lui seul, les variables type (texte étendu, groupe, caché, privé, public ...) ce qui a pour effet de brider cette option comme d'autre. 
@+

**Comment by jipexu** [comment]
oui ! cette partie du code est à parfaire ... quand le fait on ?  ... car cela fait rajouter au moins 1 champ dans la bd .... et bien entendu modifier le code dans plusieurs fichiers ...

**Comment by previnfo** [comment]
Oui, en fin de semaine cette petite modif, je vais essayer de la faire celle petite modif (histoire de me remettre dans le bouillon) \\ (sous la bienveillance de ton contrôle)... C'est le genre de bricolage qui, jadis, était à ma portée !!! Bon maintenant, c'est probablement une autre aventure (bien moins évident)

Donc, en effet, une colonne (champ) dans la table que l'on pourrai définir comme $forum_etend a rajouter dans  **phpbbforum.php** dans les lignes 296, 524, 576, 607. 
Un peu plus complexe (pour moi) ce sera l’instruction de l'apport conditionnel (if) en ligne 554.

Puis de simples rajout du nom du champ:
-pour **admin.php** dans les lignes 599 & 603
-pour **viewtopic.php** dans la ligne 516
-pour **viewtopic.phpH** dans la ligne 461
- pour **viewforum** dans la ligne 389

Les metamots ForumL & ForumP à mettre à jour et bien Evidemment updape de la SQL. 
Y a peut être encore certain trucs ?? Afaire à suivre ;-)

**Comment by jipexu** [comment]
il y potentiellement  18 fichiers à modifier ! plus la bd courante ... ça fait du boulot ! ...

**Comment by previnfo** [comment]
It's true, !!  
C'est très probable, avec un raisonnement très simpliste je me suis juste,
dans un premier temps, préoccupé du champ complémentaire à celui de "$forum_pass.."  ;-)))
