### ISSUE TITLE
Les dix dernières contribution(s) 

### ISSUE THREAD

**Issue by previnfo** [npds/npds_dune#258]
Hi there,

Dans le cahier des charges d'un Projet d’amélioration : (BETA 0.x ou BETA 1)
L'inventaire des **dix dernières contribution(s)** ne se calibre/limite qu'aux articles. 
Avis (collectif), ce serait une plus valu et source de motivation (pour le besoin d'existentiel des membres Actif) **d’étendre** l'historique de ce journal aux participations/contributions sur forums... voire même avec d'autres modules, comme liens web, les photos, les événementiels ... 

Observation complémentaire sur l'affichage actuelle de l'inventaire "des 10 dernières contributions d'articles":  il serait aussi plus 'parlant/significatif' de **rajouter** (les **dates** en phase/relation avec les (10) dernières contributions) 
@+

**Comment by jipexu** [comment]
> Observation complémentaire sur l'affichage actuelle de l'inventaire "des 10 dernières contributions d'articles": il serait aussi plus 'parlant/significatif' de rajouter (les dates en phase/relation avec les (10) dernières contributions)

==> fait

**Comment by previnfo** [comment]
Cool !!! 👍 Quel taf tu fais ... comme d'hab  ! Merci !

**Comment by jipexu** [comment]
ok en ce qui concerne les modules ce sera à développer dans les modules ...
