### ISSUE TITLE
installation auto interface

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#262]
Salut JPB, 
Voici Toutes les remarques au niveau de l'install de la version NPDS du 19-12-2017

1 - Install page 1 ==> logo toujours trop gros car il serait bien que tout soit sur une page .... de plus le logo de la taille
```
 NPDS
installation automatique
```
Serait idéal... 

2 -  Une explication sur la checkbox Installation rapide serait bien  Je ne vois pas du tout a quoi cela sert

3 - Licence avoir un bouton qui permette de refuser la licence et qui exeplique que si tu n'accepte pas la licence tu peux pas installer 

4 - Normalisation des noms du theme dans le champs Thème graphique (au moins à l'affichage)

5 -  dans ma conf, mais c'est ma conf le script ne peux pas créé la bdd. une fois créé, il crée bien les tables et le reste.

6- Pas de 6  ==> install fini

Voila

**Comment by jipexu** [comment]
2 - un tooltip ? avec quel texte ? (.... Cette option valide l'acceptation de la licence GNU/GPL V3 et supprime l'affichage des résultats de certaines opérations d'installation ....) 
4 - c'est à dire ?
5 - j'ai supprimé la possibilité de créer une base de donnée par le script car on ne sait pas faire quand on est derrière des cpanel ou autre (c'est très complexe et incertain...) ... (en principe dans le texte d'accueil c'est mentionné)

**Comment by Jireck-npds** [comment]
2 - J'en sais rien je ne sais pas ce que cela fait ....
4 - a l'affichage, on a tous les noms exotiques des themes ( pas de nomenclature), il faudrait donc : 
 Soit mettre une norme de nom de theme au moins pour ceux de base ( Majuscule au depart puis minuscule)
 Soit faire au dessus en php

5 - OK Pas de soucis

**Comment by jipexu** [comment]
2- je viens de te l'écrire ...
.... Cette option valide l'acceptation de la licence GNU/GPL V3 et supprime l'affichage des résultats de certaines opérations d'installation ....

en résumé saute des étapes d'affichage ...

**Comment by Jireck-npds** [comment]
Ben faut ecrire cela alors...
