### ISSUE TITLE
quelles infos dans popup avatar  pour membre/anonyme/admin 

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#263]
Hello

Je trouve bizarre que n'etant pas loggué en membre on puisse accéder au MI en cliquant sur l'avatar puis sur message.

La meme chose pour le "profil" 
soit on est membre et on voit le profil du gars 
Soit les profils sont public ( je sais plus si on peux)
Soit on ne voit pas la possibilité 
soit on arrive sur une page explicative, en disant que les profils sont reservé au membre ...
bref pas d'ouverture d'un nouvelle onglet retournant sans explication sur la page de garde par defaut.

**Comment by jipexu** [comment]
oui c'est anormal ..!
alors dans les popup avatar quand on est en anonyme qu'est ce qu'on laisse ?
juste minisite, site web, et reseaux sociaux ??

**Comment by Jireck-npds** [comment]
minisite, site web je dirais

**Comment by jipexu** [comment]
pas de réseaux sociaux ?

**Comment by Jireck-npds** [comment]
C'est compliqué....
Ma facon de voir est la suivante : 
soit les membres sont privé (memberslist privé, profil privé, web, RS, tout est privé donc pas de popup pour anonyme
Soit c'est semi- privé et l'admin decide ce qu'il affiche au popup ( mais pas MI normal)
soit tout est ouvert, on affiche tout sauf MI

Voila 
Par defaut, je considere les informations d'un site appartenant a ce site donc privé ... mais c'est mon choix d'admin du site.

En terme technique je dirais 
Si memberslist ( preference ) est en privé, on est en mode privé (membre only ) 
Si memberslist ouvert, il faudrait une option pour faire afficher ce que veux l'admin du site ( quitte aux membres de decide de renseigner le champs en precisant que le champs est public.
et avec les parametres du dessus on peux avoir un site ouvert.

Je dis cela sans regarder l'impact sur les modif a faire ... je reste un mode pratico-pratique.

**Comment by previnfo** [comment]
Hi there,

Bonne observation !

À mon sens pour les anonymes, on lui présente les fonctions dispo., mais avec l'instruction du genre " ...vous devez être enregistré en tant que membre pour pouvoir utiliser ses fonctions...." 

De plus, en regardant cela plus en profondeur , on s'aperçoit que même en <b>anonyme </b> on tombe étrangement/directement dans le formulaire d’élaboration d'un MP, sans que celui-ci soit réellement fonctionnel, sans information du contraire on peut toutefois penser que pour un anonyme cela soit possible. 

Pour moi, je vois plutôt, dans la même philosophie d'offrir la seule lecture aux anonymes sur un forum (avec l'avertissement de s'enregistrer pour y participer), de leurs présenter les possibilités de voir (facilement) depuis l'avatar les options qui leurs seraient offertes s'ils s'enregistrent/s'inscrivent. 

Merci à jireck pour ses justes remarques.

**Comment by Jireck-npds** [comment]
Je suis contre le inscrivez vous .... et je prefere rien 
Pourquoi ?
Parce que je fais des sites en npds sans membre et si on encode avec inscrivez vous ben impossible de ne rien avoir.
Alors que le rajout est plus simple

**Comment by jipexu** [comment]
#271 fixed
