### ISSUE TITLE
style pour input requis (required)

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#266]
Hello,

Ne pourrait on pas mettre les champs obligatoire en surbrillance quand on crée un user dans la partie admin...??

ca serait bien, il me semble

**Comment by jipexu** [comment]
oui sûr ...
j'ai regardé et il semble qu'une simple déclaration css devrait faire l'affaire ( dans la mesure ou le html est correct) .. car on doit composer avec le système de validation qui change aussi l'aspect des inputs ... donc j'ai tester ça et ça semble bien s'intégrer

dans style.css

`input[required='required']
 {
border-color: #d9534f;
 }`

dis moi si ça va et si tu vois des inputs qui n'aurait pas l'attribut required="required"  alors qu'il devrait l'avoir ....

**Comment by Jireck-npds** [comment]
Tu ne peux pas plutot utiliser la class info

**Comment by jipexu** [comment]
j'ai donc opté pour une solution souple dépendant du thème
il suffit donc de modifier dans style.css ... 

par defaut c'est un border plus épais sur l'input mis ca peut être tout autre thémisation de l'input

```
input[required='required'] {
border: 1px solid ;
}
```
