### ISSUE TITLE
Encodage sur Forump

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#268]
Avec l'install par defaut forump est installer dans l'edito et il y a RÃ©ponse 

donc à corriger

**Comment by Jireck-npds** [comment]
SystÃ¨me dans les preferences
Pas mal de chose dans l'admin ...

Bizarre... c'est sans modification plus que l'install
Je vais validé la config plus avant

**Comment by Jireck-npds** [comment]
le html est bien en utf-8
la base en utf8_general_ci
HTML5 ETC....

**Comment by Jireck-npds** [comment]
d'ailleurs j'ai les dates en english

**Comment by jipexu** [comment]
>Avec l'install par defaut forump est installer dans l'edito et il y a RÃ©ponse

>donc à corriger

j'ai supprimer l'édito membre qui ne doit pas faire partie de l'archive
oui forumP (faute dans le html et non responsive ...et plus ) n'est pas encore un métamot stable il est à revoir ....
