### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#269]
Hello,

Il serait bien de faire une todo list des choses à faire.
Genre : Meta forumP au norme, etc ...
Comme cela, on pourrais les mettre a dispo et certains pourraient s'en attribuer et les poster sur git.
Puis il n'y aurais plus qu'a les relire, les corrigé si besoin et les integrer ...
du cooperatif quoi ...

Avis comme cela

**Comment by jipexu** [comment]
https://github.com/npds/npds_dune/projects/4?

il y a tout ce qu'il faut ici pour faire et suivre ...

**Comment by Jireck-npds** [comment]
En fait Pas vraiment.....
Il vaut mieux faire un New issue avec un bon titre référencent le premier issue discutions et résumant les choses décidés ou possible.
C'est juste une question de process : 
1 idée
2 Proposition
3 discutions (pratique et technique) 
4 decision
5 CR des décisions ( <= là c'est le nouveau issue claire et synthétique )

**Comment by jipexu** [comment]
non le git doit rester consacré au développement
et les "issue" sont des" issue" 
c'est à dire des choses précises des propositions, modifications bug mais dans leur phase de réalisation ou de correction pour le reste il faut discuter sur les forums de npds
regarde sur des git très actif (par exemple boostrap ou autres) tu verras que les issues sont extrêmement strict dès que c'est hors sujet et non productif c'est fermé ...

**Comment by Jireck-npds** [comment]
Git est exactement ce que tu as envie d'en faire.
tu compare le dev bootstrap avec le dev npds..... je ne crois pas que cela supporte la comparaison.

Maintenant tu veux faire comme le git bootstrap, OK.
Je ne vois pas l'interet de multiplier les supports de com et dev. 
encore avec le labo de phr, je comprenais, pas mal de personne participait mais pas accessible a tout le monde...

Bref, **je respecte ta vision** des choses sans y adhérer.

**Comment by jipexu** [comment]
je ne compare pas je veux juste utiliser les outils pour ce qu'ils savent faire le mieux npds est idéal pour discuter proposer planifier et git pour réaliser, suivre le code et le projet dans sa partie la plus pratique et la plus rébarbative  (pas les idées ...) et quand au labo il sert de cobaye ... ça me semble cohérent

**Comment by Jireck-npds** [comment]
good
