### ISSUE TITLE
Rubrique

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#274]
dans "Ajouter une nouvelle Rubrique"
Je me suis toujours demandé pourquoi dans : Nom de la Rubrique il y avait un textarea plutot qu'un input standard.

Cela serait mieux, il me semble

**Comment by Jireck-npds** [comment]
Pareil pour le "titre" dans nouvelle sous rubrique
Pareil pour le titre dans Ajouter une publication

**Comment by Jireck-npds** [comment]
Pareil pour la FAQ
Ajouter une catégorie
Nom

**Comment by jipexu** [comment]
c'est juste parce que ces champs sont à 255 caractères (ce qui est même parfois largement insuffisant si on fait du multilangue) et donc pour saisir sereinement 255 car il est bien entendu préférable d'être dans un textarea qui est un input à plusieurs lignes ...

**Comment by Jireck-npds** [comment]
Oki Je trouve cela bizarre mais s'il faut ....
