### ISSUE TITLE
position icone visualisation dans admin Archives-story

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#276]
Ne pourrait on pas mettre le Voir le module en mode utilisation a la même hauteur que le titre mais a droite.
Ou avec un peu de texte car l'icone fait esseulé et pas très compréhensible .

**Comment by previnfo** [comment]
(+1)  je suis en phase, car je n'y avais même plus fait attention.

**Comment by jipexu** [comment]
=> fait en bas (après le form) avec texte ... car dans le titre c'est trop compliqué (car tous les titre de l'admin sont fabriqué par une routine ...)
