### ISSUE TITLE
Admin Gestion des groupes

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#277]
Hello 

J'ai un peux de mal a comprendre la mise en page.

Explication du contexte  : 
Install neuve => OK
Création d'un user pour test => OK
Et dans l'admin groupe
![groupe](https://user-images.githubusercontent.com/16939826/34710701-b75b2b44-f51c-11e7-92f8-7721494a6ce8.PNG)

1)  Ajouter un groupe => OK
2) La premiere icones avec le 0 devant je peux a peu pres comprendre, bien qu'un "groupe (s)" avec l'icones serait plus claire
3) La deuxieme icone, je me dit c'est un user => OK mais quand je deplie Je vois : 
    - Exclure du **groupe 0**  et moderateur  
Question : c'est quoi ce **groupe 0** ?
Pourquoi mon user est dedans par defaut ?

4) Comme tu peux le voir j'ai toutes les actions sur le groupe 0 ( la mise en page fais vraiment bizarre quand  tu y va pour la première fois car cela est dans seulement une moitié de page.
Peut etre que la mise en page des icones la meme chose en version horizontal serait mieux.

5) Quand on édite le groupe 0 c'est tout vide ... cela laisse perplexe.

Voila

**Comment by jipexu** [comment]
point 4 ok il y avait une faute quand on avait pas d'image...
