### ISSUE TITLE
[tiny] menu multi langue npds accessible sur un site non multilangue

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#282]
Hello Jpb

A moins que cela est changer ( c'est possible....) 
Lorsque dans mes "preferences" je selectionne Francais et multilangue "NON"
Dans l'editeur, panneau deroulant "langue", on a toujours la possibilité de seldction autre chose que francais. 

Avec l'option Activer le multilangue a NON on ne devrait pas avoir le panel "langue" dans l'editeur.

**Comment by jipexu** [comment]
jamais fait attention à cela
oui logique ce que tu dis ... c'était probablement comme ça avant ... il doit manquer une implémentation ...

**Comment by Jireck-npds** [comment]
Je pense que cela serait de faire cette modif

**Comment by jipexu** [comment]
fixed by #291
