### ISSUE TITLE
[template tiny] url du template introuvable quand site n'est pas à la racine

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#283]
Bonjour Jpb,

Pourrais tu me rappeler / dire : 
1 ) Comment on accede au template npds dans l'editeur
2) Comment on crée un template personnalisé (stockage et modif)

Bug ou je ne comprends pas ou pas fonctionnel chez moi : 
Quand je click sur inserer > template
![template](https://user-images.githubusercontent.com/16939826/35765868-6fb01e20-08cd-11e8-92d2-4f41dd21de6a.PNG)

Je peux selectionner un format mais rien ne se passe ...

**Comment by jipexu** [comment]
Bizarre est ce que tu as des erreurs js dans ta console ?
Est ce que tu as bien tout les fichiers dans tiny ??
.... car en principe ta zone de saisie devrait contenir l'exemple du template .... (je regarde quand meme  si l'archive est complete) sinon il faudra que tu cherche dans ces directions (les templates js absent ?....) dans ton install ??

**Comment by Jireck-npds** [comment]
En local ca marche mais pas sous free.fr

et pour avoir une template personnalisé .... tout semble avoir disparu... ?

**Comment by jipexu** [comment]
ah alors il doit y avoir un probleme d'url .... je pense que tu dois avoir une erreur js mentionné dans ta console ...

**Comment by jipexu** [comment]
dans /editeur/tinymce/themes/advanced/npds.conf.php

tu as l'appel des templates est ce que cet appel est correcte pour ta config ????

**Comment by jipexu** [comment]
... ou droit de ces fichiers ?

**Comment by jipexu** [comment]
pour la question 2 tu as donc en partie la réponse
- création d'un template html
- et déclaration de cet élément dans l'objet (dans npds.conf.php) ...

**Comment by Jireck-npds** [comment]
Il n'y a plus d'exemple ... je vais chercher
Finalement, c'est l'inverse...

Chez free cela fonctionne
et en local cela ne fonctionne pas 
The requested URL /editeur/tinymce/plugins/template/txt_1_col_12.html was not found on this server.

Avec la derniere version..

**Comment by Jireck-npds** [comment]
Apres verification c'est une erreur d'url ....

Il me prends pas mon sous repertoire ...

**Comment by jipexu** [comment]
donc comment on corrige ? rajout de $nuke_url  dans npds.conf.php ???

**Comment by Jireck-npds** [comment]
Il serait bien d'avoir une confirmation par une autre personne

**Comment by previnfo** [comment]
Hi there,
De mon cote, je n'ai aucun problème avec les Templates NPDS dans l’éditeur tiny MCE ...
Je vais essayer en local (winamp) pour voir >> 5 mintes !!

**Comment by previnfo** [comment]
Fonctionnel en local aussi ...

**Comment by jipexu** [comment]
avec quelle url ? le portail est à la racine ?

**Comment by previnfo** [comment]
Ben pour moi j'ai les url de la racine pour local (http:.....:8000/submit.php) & pour prev (http://pre.../submit.php) .. donc à mon niveau pas de soucis d’interprétation d'url ou d'url en dur.

Si c'est bien cela qui est tracé ?

**Comment by Jireck-npds** [comment]
non c'est plutot un http://monsite.fr/npds/

**Comment by jipexu** [comment]
donc c'est bien ça faut rajouter la racine dans le conf de tiny .....

>> donc comment on corrige ? rajout de $nuke_url dans npds.conf.php ???

**Comment by jipexu** [comment]
Donc vous confirmez donc bien que l'appel du template ne fonctionne pas quand le site n'est PAS à la racine ?..

>> http://monsite.fr/npds/

**Comment by previnfo** [comment]
C'est probable ... mais moi je ne peux le confirmer.    
Mon site n'est pas dans la racine de mon serveur (un sous répertoire), mais ayant instruit ce répertoire comme (racine du nom de domaine), il est fort probable que c'est pour cela que je ne peux reproduire / voir le problème précité. 

À confirmer !!

**Comment by jipexu** [comment]
mais en local il te suffit juste de mettre l'ensemble dans un dossier pour tester temporairement et confirmer ou pas ...?

**Comment by previnfo** [comment]
Le problème est qu'il me semble bien que j'ai déjà mon site dans un dossier ou sous dossier.... 
>>>> Bon,  je vais toutefois revérifier avant de dire qu'il n'y a pas ce soucis ....  !! (une petite 1/2heure le temps redémarrer mon vieux PC ...) 
Je vais faire cela et te fais un retour !

**Comment by jipexu** [comment]
merci

**Comment by previnfo** [comment]
Ben c'est ce que je viens de faire  rajouter un dossier basculer et tester ... 
 http://www../npds/    chez moi, il reprend correctement la racine et je n'ai pas  le PB template précité. 
A moins qu'il faille encore produire autre chose.

**Comment by jipexu** [comment]
fixed by #291 ??? on rouvre si probleme...
