### ISSUE TITLE
Question Editeur ( Forum // Article ) 

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#285]
Salut 
Pourquoi les editeurs sont different entre celui des articles et celui des forums

Normalement, celui des forum devrait etre une version courte des articles...
Au moins dans le design....
non ?

**Comment by jipexu** [comment]
tu parles de tiny ? dans le forum ? comprends pas ta comparaison

**Comment by Jireck-npds** [comment]
![1](https://user-images.githubusercontent.com/16939826/35769037-4338339a-0905-11e8-8f58-4c1ecae25b70.PNG)
![2](https://user-images.githubusercontent.com/16939826/35769038-4572825a-0905-11e8-9fe6-741a8f5b29ea.PNG)

Voila la difference

**Comment by jipexu** [comment]
ah ça et ben c'est historique lol ... tu as déjà vu tiny dans un forum de npds ?
... pourquoi j'en sais rien ...

**Comment by previnfo** [comment]
Hello,
Je ne sais pas pour la V16, mais sur la V13, **jireck** tu avais déjà proposé une solution qui fonctionnait bien :
dans -> **page.php** :

> $PAGES['reply.php'][TinyMce]=1;
> $PAGES['reply.php'][TinyMce-theme]="short"; 

et le code  ---> echo aff_editeur("message", "true"); <---   à  reply.php apres le textaera 

Il fonctionnait encore mieux avec le rajout dans "**pages.php**" et du précédent bout de code dans "**editpost.php**"
> $PAGES['editpost.php'][TinyMce]=1;
> $PAGES['editpost.php'][TinyMce-theme]="short"; 

Je dirai même que l'insertion des smileys fonctionnait relativement "mais comme une image", car il suffisait de glisser celle que l'on voulait dans l’éditeur tiny.

Maintenant, s'il n'y a pas d’interférences avérées/soupçonnées éventuellement offrir (en option) ce choix
aux webmasters. _Probablement en rajoutant dans l'admin le champ d'une condition et les "if"  dans les php impacté..._ 

@+

**Comment by jipexu** [comment]
peut on repasser ce genre de post sur le forum de npds ...

**Comment by Jireck-npds** [comment]
Bref c'est clos mais cela réponds pas à la question.


Mettre le même design sur les 2 pages où l'editeur est appelé, que ce soit l'un ou l'autre.

**Comment by jipexu** [comment]
mais tu parles de quoi de design ou de fonctionalités
>>Mettre le même design sur les 2 pages où l'editeur est appelé, que ce soit l'un ou l'autre.

dans un cas tu as un appel de l'editeur (tiny) mais dans les forums c'est le pseudo editeur interne de npds donc je ne vois toujours pas la logique de comparer un choux et une carotte et de vouloir les faire se ressembler ...

alors si ta question est pourquoi il n'y a pas tiny dans le forum c'est un autre débat loin d'être simple à décider puis à implémenter... c'est pour cette raison qu'il faut ouvrir un post sur npds

**Comment by Jireck-npds** [comment]
> dans un cas tu as un appel de l'editeur (tiny) mais dans les forums c'est le pseudo editeur interne de npds donc je ne vois toujours pas la logique de comparer un choux et une carotte et de vouloir les faire se ressembler ...

Pourquoi utiliser un pseudo-editeur interne... ? 

> c'est pour cette raison qu'il faut ouvrir un post sur npds

Je paris 10 € que cela ne serait jamais ouvert en même temps. sur NPDS,
Et si c'est le cas, y'a pas plus que de personne pour donner son avis. 

Maintenant, j'ai compris ton principe de separé le code et le blabla, ne t’inquiète pas
