### ISSUE TITLE
Forum | case a cocher 

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#287]
Hello 

Pourrait on m'expliquer la case a cocher " Marquer tous les messages comme lus" 
![1](https://user-images.githubusercontent.com/16939826/35777204-2bb34124-09aa-11e8-889f-86e80d2b2fff.PNG)

C'est une option sans validation avec OK, c'est une option admin / membre

car pour un nouveau membre et de grosse table de forum si c'est automatique cela va beaucoup solicité la base etc ...

**Comment by jipexu** [comment]
rien de changé par rapport à une 13 .. (à part l'interface)
oui pour un nouveau membre et sur sa première mise à jour, la base est sollicité pour mettre à jour la table forum_read. donc oui plus les mises à jour de la table sont espacés et plus il y a de requête mais comment faire autrement que de solliciter la base pour la mettre à jour...
