### ISSUE TITLE
html dans Forum description

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#293]
Hello JPB

Je viens de voir que l'ecriture de la description d'un forum
Le retour clavier ne sont pas pris en charge...
Il me semble qu'ils etaient pris en charge avant ...

**Comment by Jireck-npds** [comment]
Le br oui

**Comment by jipexu** [comment]
je ne vois pas exactement ce que tu veux dire ... (si c'est le return pour valider le form ou le return dans le input description ...)
mais je crois qu'il y a un problème quand on édite un forum groupe on a pas la valeur du groupe (et ceci annule le return de validation vu que l'id du groupe est obligatoire) ... tu confirmes ??

**Comment by Jireck-npds** [comment]
Précision c'est la touche  "Entrée" retour a la ligne qui n'est pas pris en compte.
Il faut mettre BR pour le retour a la ligne.
En meme temps si on pouvais mettre le pseudo editeur a ce niveau ce serait bien ... mais c'est autre chose ca

**Comment by jipexu** [comment]
ah je comprends ce dont tu parles c'est de pouvoir mettre plus facilement du html dans la base pour la description du forum .... ce qui n'est pas le cas actuellement

**Comment by Jireck-npds** [comment]
oui 
mais le premier probleme c'est par exemple si je tapes 

1/ ecrivez
2/ lisez
3/ hohoho

Cela m'affiche 
1/ ecrivez 2/ lisez 3/ hohoho

Sans retour chariot

**Comment by jipexu** [comment]
donc on perd le retour chariot durant l'aller retour avec la base c'est ça ?
