### ISSUE TITLE
lnl.php

### ISSUE THREAD

**Issue by scrameustache** [npds/npds_dune#295]
Salut,
Dans le fichier lnl.php, ligne 74, il y a deux EE dans INSERT INTO
`sql_query("INSEERT INTO ".$NPDS_Prefix."lnl_outside_users VALUES ('$xemail', '$host_name', '$timeX', 'OK')");`

**Comment by jipexu** [comment]
belle trouvaille merci

**Comment by jipexu** [comment]
fixed with #295
