### ISSUE TITLE
Admin gestion des commentaires (all comment) dans NPDS

### ISSUE THREAD

**Issue by previnfo** [npds/npds_dune#297]
Hi there, 
Je pense qu'il serait utile d'avoir un petit mod pour un admin en mesure de surveiller ou d'administrer beaucoup plus rapidement l'ensemble des commentaires qui pourrait être laissé dans NPDS ou l'option "commentaire" a été instruit via le meta "system_comment" ou simplement par défaut comme pour les articles &.... 

(A moins qu'il existe une option de notification que je ne connais pas ?) 
En effet actuellement, il faut vraiment passer sur l’article pour s'apercevoir qu'il a été commenté, et ainsi pouvoir y répondre ou (si c'est une pub) pour l'administrer.  

Avec un site avec plus de 300 articles & autres utilisant les commentaires, on perd totalement la maîtrise de ces informations qui s'y instruisent. 

En effet, je me suis amusé via la DB à collecter les infos qui circulaient dans les ID forum négatif ("-" couvrant apparemment les commentaires) & me suis bien aperçu que ces espaces commentaires étaient devenus un terrain propice à de la publicité (au meilleur des cas...!) 

Je sais qu'un petit "meta" ne serai pas complexe à produire pour au - faciliter la lecture de ces x commentaires, mais une option + consolidée intrinsèque à NPDS pour les surveiller/administrer, serait a mon avis bien utile... 

@+

**Comment by Jireck-npds** [comment]
A mettre dans un patch amélioration fonctionnel (qui sortira après la nouvelle version)
