### ISSUE TITLE
Alerte email super-administrateur pour commentaires

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#302]
Salut JPB,
Est ce que tu prends encore des améliorations ? 

Si oui : 
Dans le fichier reply du répertoire modules/comment, il faudrait ajouter ligne 136 : 

`
// Jireck 20-03-2018

if ($notify) {
	  global $notify_email, $nuke_url, $notify_from;
		$csubject = 'Nouveau commentaire sur '. $nuke_url;
		$cmessage = '<a href="'. $nuke_url. $url_ret.'> Nouveau commentaire sur '. $url_ret.'</a>;
       // OU mieux au dessus
        send_email($notify_email, $csubject, $cmessage, $notify_from , false, "text");
}

`

Afin que l'admin soit averti des nouveaux commentaires par mail ...
Utilise $notify comme pour les submit de news mais peut etre declarer autre chose dans les pref a voir suivant ta volonté.
$notify est déjà bien car une personne qui est notifier pour les news trouvera bien d’être notifier pour les commentaires

**Comment by previnfo** [comment]
Hi there,
Ne serait ce pas plutôt (?) ...
$cmessage = '<a href="'. $nuke_url.'/'.$url_ret.'>Nouveau commentaire sur '. $url_ret .'</a>';

Sinon +1 pour cette amélioration ! 

(en transit, à bientôt !)

**Comment by Jireck-npds** [comment]
A mettre dans un patch amélioration fonctionnel (qui sortira après la nouvelle version)

**Comment by previnfo** [comment]
=> A maintenir en projet d'amélioration  !!!

**Comment by Jireck-npds** [comment]
oui faut faire un classement pour mettre en patch toutes les améliorations

**Comment by jipexu** [comment]
en cours d'implémentation !

**Comment by jipexu** [comment]
Ok c'est implémenté.
NB : cependant il n'est pas possible d'utiliser la signature à cause du nom de la variable $cmessage. J'ai pas fait tous les essais pour lui attribuer le nom $message (seul nom compatible avec signat.php) car on a peut-être des possibilités de conflit car $message est largement utilisé (...pour le message du commentaire ....) ... mais bon c'est pas très grave on peut se passer de la signature ...
