### ISSUE TITLE
Piece Jointe forum

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#325]
Pourquoi les pieces jointes au forum sont maintenant par defaut replier ?

Peut on les deplier par defaut ?

**Comment by jipexu** [comment]
c'est une question qu'on s'est posé et j'avais donc modifié en conséquence  pour plus de clarté dans le post mais bon c'est un détail qu'on peut rechanger  (d'ailleur je vois que sur le labo j'ai le comportement inverse ...).. en tout cas ce n'est pas paramétrable autremebnt que dans le code ...

**Comment by Jireck-npds** [comment]
Je pense que les 3 option serais bien 
1 Replier et affichant le nom du fichier sur lequel on clique 
2 replier et affichant la piece jointe
3 deplier et affichant la piece jointe
