### ISSUE TITLE
Avatar Bis

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#327]
Bonjour, 

Comme annoncé, J'ai passé ma taille d'avatar a : 200*200

Mais NPDS maintenant s'en fout

Dans les forum je me retrouve avec un avatar Resizer en 64*64

Y'a un probleme là car si j’augmente ma taille d'avatar c'est pas pour avoir un resize
Surtour en 1920*1080

**Comment by jipexu** [comment]
non y'a pas de problème c'est juste un choix

**Comment by Jireck-npds** [comment]
A si c'est un Bug
Explication : 
Tu as envie de voir des grandes images en avatar (comme je veux) tout en restant responsive.
Donc tu choisi le format 200*200
Sur un grand ecran (>900px) tu dois avoir les image en 200*200
Sur tablette ou mobile tu dois avoir l'image resize correct pour l'affichage
Precision : je parle de l'avatar pas les images de moderateur ou posteur qui sont en haut du forum.

Sinon La variable ne sert plus a rien, et il est impossible de changer quoi que ce soit.

**Comment by Jireck-npds** [comment]
si le gars met du 1 normalement dans ton exemple il y aura un affichage standard d'un 1*1 dans une boite de 200*200 pour que l'affichage soir conforme.

De plus si l'admin met du 200*200 ou 400*400 c'est qu'il veux un affichage comme cela sur grand ecran.

Generalement, Moi, mes avatars par defaut je les met en 200*200 en plus de l'upload a 200*200

et cela fonctionner parfaitement meme avec un avatar uploader a 1*1.

Maintenant je peux comprendre si tu me dit que le parametre de taille et la taille des avatars par defaut sont plus necessaire car BS ou le Code ne sait pas faire un affichage correct si on change ces valeurs.

Mais je trouve cela anormal alors oui ce n'est pas un bug car l'affichage est correct mais c''est pour moi une regression de fonctionnalité.

Malgre tout je continu : 
si tu choisi un 200*200 ou même 600*600, l'avatar devrait s'affiché correctement sur les affichages "Grand" ou "Bureau" bref supérieur à 900.

Par contre il devrait avoir un resize immediat en cas de passage sous les 900.

Je te met l'image capture pour te donner un exemple
![capture](https://user-images.githubusercontent.com/16939826/41421388-03ed79c6-6ff7-11e8-8847-1d110945adcb.PNG)


Comme tu peux l'imagine, J'aimerais bien avoir un 200*200 qui occupe la place
Mais les icones poster et moderateur sont pour moi OK

**Comment by jipexu** [comment]
je ne comprend pas ton raisonnement
dans une Rev 13 on avait pour la même portion de code un div avec la classe avatar_cadre fixé par la css (un carré de 98 par 98) et c'est tout
que vient faire la dimension qui n'est utilisée que pour la limite supérieur de l'upload ? et qui n'a jamais été disponible à ce niveau ?..
Alors pourquoi tu parle de regression de fonctionnalité c'est juste une approche différente ... 

bien sûr tu peux ré-écraser la classe n-ava mais comme certains des éléments sont en position absolute il faut re-bricoler le code aussi ..... 

Mais franchement je ne suis pas chaud pour rendre ces avatars responsive car ici je cherchais justement à faire l'inverse vu qu'il s'agit d'un icone (qui plus es un "bouton") pas d'une image simple ...

**Comment by Jireck-npds** [comment]
Non Il y avais un class avatar_cadre qui ne fixais rien
```
.avatar_cadre {
    text-align: center;
    margin-bottom: 5px;
}
```
La régression est que maintenant c'est du 64*64 donc c'est pas des avatars c'est des icones...

 juste ouvre l'image que j'ai uploader et ru trouvera qu'il ni a aucune difference entre lesicones et les avatars et que le 64*64 c'est ridicule d'autant que l'upload est en 80*80...

Mais je peux comprendre ton desir de silmplification

Donc on va rester simple Ne touche rien et clos le sujet

**Comment by jipexu** [comment]
si ... permanent double side ... à une classe qui fixe à 98 98 !!

comme je te l'ai dit il n'y a aucun "pont/lien" entre la dimension maxi autorisé pour l'upload et l'affichage ... c'est probablement un manque mais c'est tout ...

donc tu peux bien écraser la classe n-ava... si tu veux la changer comme tu pouvais le faire dans une 13 ....

**Comment by Jireck-npds** [comment]
Un des trucs qu'il aurait été bien de faire etant de scinder par des divs comme avant les posts.

La solution etait pour moi comme ca.


```
<div class=card post>

<div class= posterfull> // toutes les infos sur le poster
<div class= Avatar>
<img class= fullsize responsive />
</div>
<div class= memberqualify>
Nb post
</div>
</div> // FIN  infos sur le poster
<div class= posterfull>
Text du post + File upload si il y a 
</div>

<div class= card footer>
</div>
</div>


```
