### ISSUE TITLE
[ A confirmer ] Menu responsive

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#330]
Bonjour 
Lorsqu'on est configurer sans bloc a droite et a gauche, en responsive on a le hambuger pour depiller les colonnes.
Donc pas normal

**Comment by jipexu** [comment]
quel thème ?? tu parles de l'icone en haut à droite dans la barre de menu ? celui-ci déplie les menu pas les colonnes?..  les colones c'est avec le texte plus de contenu moins de contenu ....
