### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Pascal66** [npds/npds_dune#335]
Content de voir npds en bonne forme !
Est-ce que je peux upgrader ma version 13 comme je le fait depuis de nombreuses années en écrasant tout les fichiers sauf config ?

**Comment by Jireck-npds** [comment]
Non il y a des update de base de données

**Comment by Pascal66** [comment]
Je ne peux pas effacer la foultitude de choses que j'ai depuis 15 ans de npds...

**Comment by jipexu** [comment]
oui comme ji le dit il faut modifier la base et pour l'instant on a pas de script pour cela donc il faut un peu bricoler ... faire une install neuve et réintégrer les données de la base
