### ISSUE TITLE
Question : Geoloc

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#340]
Hello 

Juste pour savoir si geoloc va reste dans le core ou passé en module maintenant que c'est payant ?

**Comment by Jireck-npds** [comment]
Et integré au core ?
Le mieux etant de tout mettre en module comme je l'avais dit.
Avec le systeme d'onglet dans user.php pour les module le permettant.

**Comment by jipexu** [comment]
réponse dans forum npds...

**Comment by Jireck-npds** [comment]
Pas vu pas pris.
