### ISSUE TITLE
SFORM mise en page

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#363]
Bonjour jpb,

Comme je pense et je l'ai dit, je ne vais pas te proposer d'amelioration de Sform, bien que cela serait genial (passera a la trappe dans ma memoire).

Juste pour dire il me semble qu'il serait bien d'enlever le br ligne 828 du sform.php 
c'est de P donc il serait mieux pour l'affichage que ce soit en ligne

**Comment by jipexu** [comment]
Yo
pour l'instant à l'affichage on a ça ... (par exemple dans /user.php)

mon champ
**contenu de mon champ contenu de mon champ contenu de mon champ** 

tu proposes ça ? ==>

mon champ **contenu de mon champ contenu de mon champ contenu de mon champ**
(ce qui sera vilain sans deux points)

? ? ou une autre structure html ??

**Comment by Jireck-npds** [comment]
Exact il faudrait mettre : 
c'est un P dans sans soucis cela condensera les info et prendra un peu plus de place pour les grands ecrans.
![image](https://user-images.githubusercontent.com/16939826/46742437-4ee47580-cca7-11e8-8028-b9e51e4d80c6.png)

Là c'est juste supprimer le br ca reste responsive first et convient mieux au version plus large

Dans la version que je garde c'est fait la mise en page dans le aff_formulaire.

**Comment by Jireck-npds** [comment]
Comme cela suivant les cas, moi dans aff_formulaire je mettrais un col-3 et c'est plus accessible ...
