### ISSUE TITLE
Password Admin

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#374]
Derniere release.
Installation Classique sauf la contrainte du mot de passe complexe.... pas glop pas glop.
Il m'oblige a un caractere ni numerique ni alphabetique ok 
Avec la base sans encryptage
Je tape &é" ==> et ca me converti en &Ã©" donc un probleme avec les caracteres é ou è J'ai pas tester ... a moins que ce soit a cause de l'encodage mais je ne pense pas ...

**Comment by jipexu** [comment]
ah faut que je test ... c'était probablement le cas avant ??? (ca doit le faire juste avec encodage en utf8 ?)  
ceci dit le non cryptage des mots de pass dans la base est pour moi une faiblesse  de npds  et devrait ne plus etre possible ?? non ?

quand a la complexité du mot de passe cela correspond aux recommandations ...

**Comment by Jireck-npds** [comment]
Avant je pense que cela marchait mais aucune garanti.
Cela peut être l'encodage utf8, mais je suis dans l'installation simplifié.... mais je vais pas m'avancer 
Question Cryptage de mot de passe, il est preferable de garder le Non cryptage de la base. 
Pourquoi ? car c'est super-pratique pour le test ou les mini-sites, sans facteur de risque, ou jemenfoutsicesthackercestgratuit ... Par contre ajouter des preconisations du genre si votre site est en production passer l'encryptage à Yes

Dernier point c'est juste que la lib indique des truc bizarres : 
un caractere ni numerique ni alphabetique ==> un caractere spécial

Et je t'avoue que  passer d'un mot de passe faible a SuperFort en tapant 1 caractere en plus ... la lib fume un peu

**Comment by jipexu** [comment]
non en utf8 je ne vois pas comment ça pouvait fonctionner ...

donc on a bien ce problème avec un site en utf8 et des passes non cryptés ...

>Et je t'avoue que passer d'un mot de passe faible a SuperFort en tapant 1 caractere en plus ... la lib fume un peu

j'ai changé la logique de l'interface rouge c'est pas bon vert c'est bon je ne vois pas comment on peu faire plus simple et tant que c'est rouge on sait pourquoi avec les messages il n'y a plus de logique de faible fort super fort ....

**Comment by jipexu** [comment]
c'était les anciennes valeurs .... on peut monter a 40 maxi (bd) ... qu'est ce que tu proposes ?

**Comment by Jireck-npds** [comment]
2 choix, soit on met a fond mais je doute de l'interet, soit, et c'est ma preference on limite a 20.
avec la complexité ce va être suffisant.
A titre d'exemple en entreprise, pour les compte avec pouvoir je suis a minimum 16 caracteres (complexifié)

**Comment by jipexu** [comment]
ok donc maxi 20

**Comment by Jireck-npds** [comment]
Nickel

**Comment by Jireck-npds** [comment]
Donc je fais des issues pour la nouvelle version?
Bug affichage etc... ?

**Comment by jipexu** [comment]
fait aussi dans install idem 20 car maxi
