### ISSUE TITLE
Gestionnaire Fichier : typo, modèle conf, création conf pour non superadmin == problème

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#375]
Y'a une erreur de frappe ou autre 
![image](https://user-images.githubusercontent.com/16939826/47420937-d807ac00-d77f-11e8-8ab6-e94cb53f1157.png)

**Comment by previnfo** [comment]
Hi,
Where ? 
![2018-10-24_14-34-54](https://user-images.githubusercontent.com/29662021/47430689-5e30ec00-d79a-11e8-9c34-2ea7405d9dc1.png)

**Comment by Jireck-npds** [comment]
Deja bizarre qu'on est pas la meme image ..??

**Comment by previnfo** [comment]
oui

**Comment by jipexu** [comment]
?? un fichier pas mis à jour ??

**Comment by Jireck-npds** [comment]
Si c'est a moi que tu parle jpb c'est l'archive integrale recuperé de la 16.2

**Comment by jipexu** [comment]
ce qui ne veux pas dire que tous les fichiers sont bien passés pendant le transfert ?? est ce que le fichier themes/default/html/modules/f-manager/f-manager.html est correct ?

**Comment by jipexu** [comment]
>ce qui ne veux pas dire que tous les fichiers sont bien passés pendant le transfert ?? est ce que le fichier themes/default/html/modules/f-manager/f-manager.html est correct ?

??

**Comment by Jireck-npds** [comment]
Oui il est correct

**Comment by jipexu** [comment]
c'est en local ?

**Comment by jipexu** [comment]
est ce que dans le thème que tu utilises  le dossier /html/modules/f-manager/ ne contient QUE index.html ?

**Comment by Jireck-npds** [comment]
non il est en ligne sur free et comme dit il y a tous les fichiers de l'archive
![image](https://user-images.githubusercontent.com/16939826/47601047-34aad700-d9cb-11e8-83f7-2bf3747bbf8a.png)

**Comment by jipexu** [comment]
de quel dossier il s'agit ?

**Comment by Jireck-npds** [comment]
> de quel dossier il s'agit ?
default/html/modules/f-manager/ 

Sinon oui, dans l'archive donc sur mon site, le theme npds-boost_sk il n'y a que le fichier index.html

**Comment by jipexu** [comment]
donc ca c'est bon  pour l'architecture

**Comment by jipexu** [comment]
on est bien sur l'url basique ?
/admin.php?op=FileManager
ce que je ne comprend pas c'est que le html du rendu n'est pas conforme ... peut tu faire une copie du fichier ici ?

**Comment by Jireck-npds** [comment]
> Oui il est correct
> 
> Je viens de le remplacer par celui qui est en ligne et pareil

C'est celui qui est en ligne.
themes/default/html/modules/f-manager/f-manager.html

**Comment by bmag-npds** [comment]
même prob sur npdslabo2.free.fr,

**Comment by jipexu** [comment]
@bmag-npds 
sur  npdslabo2.free.fr  le theme que tu utilise n'est pas à jour ... ( car je ne l'ai probablement pas mis à jour dans le labo ...) il appelle 
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap-table.js, line 0)
alors qu'il devrait appeler boostrap-table.min.js   ......

**Comment by Jireck-npds** [comment]
Alors Voila les operatrions réalisées : 
DL de l'archive via la news NPDS
Suppression de tous les fichiers sur mon site free
ajout htacces
Uploade des fichiers npds (il y sont tous)
Install via l'installeur
Login admin 
lancement du gesyionnaire de fichier et c'est pareil

**Comment by jipexu** [comment]
donne moi un compte admin sur ton site de test ..

**Comment by Jireck-npds** [comment]
Compte Admin ==> message privé npds

Remarque c'est bizarre que quand on crée un compte admin avec les droits filemanager le fichier conf ne soit pas créé.
obligé de le créer à la main

**Comment by jipexu** [comment]
@Jireck-npds 
merci je viens de regarder dans le  theme npds_boost_sk dans le dossier /html/modules/f-manager/
tu as f-manager.html  ce fichier ne devrait pas se trouver la ... (...il n'est pas dans l'archive ....)

>dans le dossier html/modules/f-manager/ de ton theme tu dois avoir SEULEMENT index.html et rien de plus sinon tu écrase le défaut ...

**Comment by jipexu** [comment]
>Remarque c'est bizarre que quand on crée un compte admin avec les droits filemanager le fichier conf ne soit pas créé.
obligé de le créer à la main

tu veux dire que quand tu cree un nouvel admin lors de l'install il n'y a pas de création de fichier de conf du filemanager ??

**Comment by Jireck-npds** [comment]
c'est moi qui l'ai rajouté afin de voir si il prenais pas un autre fichier ... tu peux meme le supprimer c'est la meme chose avec le default c'est le fichier default d'ailleurs

**Comment by jipexu** [comment]
ok on va le supprimer

**Comment by Jireck-npds** [comment]
non quand j'ai créer ton compte admin il ne crée pas le fichier conf alors que tu est filemanager right

**Comment by jipexu** [comment]
tu l'as créé ? car je le vois il existe ...

**Comment by Jireck-npds** [comment]
oui sinon tu n'avais pas acces au filemanager donc je l'ai créer

**Comment by jipexu** [comment]
ca ne me semble pas normal ca ...
==> pour la faute sur l'accent on a une faute dans l'archive .....je la corrige ...

**Comment by jipexu** [comment]
de plus ligne 160 du conf généré
   $themeG_fma="f-manager-banque.html";
devrait être je pense ....
   $themeG_fma="f-manager.html";

**Comment by Jireck-npds** [comment]
de quel conf ?

**Comment by jipexu** [comment]
sur le labo quand je crée un admin j'ai la création de son fichier conf je vais regarder pourquoi ca ne fonctionne pas sur free ????

**Comment by jipexu** [comment]
>de quel conf ?
du conf généré (donc probalement du modele admin)

**Comment by Jireck-npds** [comment]
le fichier jpb.conf.php ?

**Comment by Jireck-npds** [comment]
ou sur le labo

**Comment by jipexu** [comment]
aussi !

**Comment by jipexu** [comment]
ce que je veux te dire c'est que le modèle n'est pas juste je pense ... on devrait avoir 
$themeG_fma="f-manager.html";

**Comment by Jireck-npds** [comment]
c'est basé sur celui du root de l'install

**Comment by jipexu** [comment]
non sur modele admin ....

**Comment by jipexu** [comment]
~/Documents/developpement/npds_dune/revolution_16/admin/authors.php:452:        @copy("modules/f-manager/users/modele.admin.conf.php","modules/f-manager/users/".strtolower($chng_aid).".conf.php");

**Comment by jipexu** [comment]
donc ce fichier pour moi devrait avoir 

$themeG_fma="f-manager.html";

**Comment by Jireck-npds** [comment]
> non sur modele admin ....

Celui que j'ai créé pour toi, Copier coller de celui créé pendant l'install pour le compte Root (premier compte admin) et renommage du fichier

**Comment by Jireck-npds** [comment]
Done

**Comment by jipexu** [comment]
merci

**Comment by jipexu** [comment]
la génération du fichier conf fonctionne ....
regarde testadm  ( que je viens de créer il a son fichier conf)

**Comment by jipexu** [comment]
je viens de publié sur github donc tu peux récupérer modele.admin.conf.php et f-manager.banque.html et faire un essai de création d'un nouveau admin  ...

**Comment by jipexu** [comment]
donc ensuite il faudra voir ce qui se passe durant l'install ...si on a une faute ..?

**Comment by Jireck-npds** [comment]
> la génération du fichier conf fonctionne ....
> regarde testadm ( que je viens de créer il a son fichier conf)

Marche pas !
Ca doit marché quand tu met super admin 
Mais si tu met juste "Gestionnaire Fichiers" le fichier ne se cré pas

**Comment by Jireck-npds** [comment]
j'ai pas encore updater les fichiers

**Comment by jipexu** [comment]
>Marche pas !
Ca doit marché quand tu met super admin

<== oui

>Mais si tu met juste "Gestionnaire Fichiers" le fichier ne se cré pas

<== ah interessante piste

**Comment by jipexu** [comment]
pourtant ca devrait sauf si on a une variable ou un test defaillant ici
authors.php ligne 522
      // Copie du fichier pour filemanager
      if ($add_radminsuper or $add_radminfilem)
         @copy("modules/f-manager/users/modele.admin.conf.php","modules/f-manager/users/".strtolower($add_aid).".conf.php");
      global $aid; Ecr_Log('security', "AddAuthor($add_aid) by AID : $aid", '');

**Comment by Jireck-npds** [comment]
Je check pas le code ... Je fais juste le test avec le nouveau compte toto pour le coup, avec le droit seul droit filemaneger

**Comment by jipexu** [comment]
arghh je vois (je pense que cette variable et donc cette comparaison n'ont plus lieu d'être car en fait dans la nouvelle admin elle a été remplacé par le droit sur la fonction ....et donc ce champ dans la base table authors  ne sert plus à rien .....)  ... bon faut que je réfléchisse comment on nettoie ça ....

**Comment by jipexu** [comment]
donc oui ca ne peut pas fonctionner ....

**Comment by Jireck-npds** [comment]
Super

**Comment by Jireck-npds** [comment]
c'est bete qu'on ne puisse pas downloader un fichier.
C'est une fonction qui me manque.
Souvent j'edite en ligne au lieu de DL modifier puis Upload ... je prefere bosser en local

**Comment by jipexu** [comment]
sur github ?

**Comment by Jireck-npds** [comment]
non via le filemanager

**Comment by jipexu** [comment]
ok c'est fixé
