### ISSUE TITLE
Champs Non prerempli dans les Preference

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#377]
Petit problème : 
Avec le collapse et sur une nouvelle install
le champ Compte E-mail (Provenance) n'est pas rempli par défaut mais obligatoire.
Donc quand tu essaie de valider autre chose rien ne se passe et surtout tu ne sais pas pourquoi rien ne se passe (merci collapse).
2 solutions : 
1/ rempli le champ avec un truc par defaut
2/ faire afficher le champs en rouge lors de la soumission

**Comment by jipexu** [comment]
fixé par #383
