### ISSUE TITLE
Image manager

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#378]
Hello 
Peux tu m'expliquer sont fonctionnement, je ne comprends pas ...
Je clique sur "images manager" et la je me balade sur l'arborescence et rien ne s'affiche a part les repertoires.

![image](https://user-images.githubusercontent.com/16939826/47428768-91707c80-d794-11e8-9559-66d4f2c98248.png)

Y'a un bug ou bien

**Comment by previnfo** [comment]
Effectivement,
en sus il semble y avoir cette erreur 
Warning: array_key_exists() expects parameter 2 to be array, null given in ../modules/f-manager/pic-manager.php on line 86

**Comment by Jireck-npds** [comment]
Je n'ai pas la notice

**Comment by previnfo** [comment]
La notice je l'ai eu lors de la lecture d'un répertoire (que j'avais préalablement autorisé => picmanager)

**Comment by jipexu** [comment]
je ne suis pas spécialiste du file manager mais il me semble que ce comportement est normal
- si il n'y a pas d'autorisation picmanager (le petit fichier)  on ne voit que les répertoires
-  si il y a autorisation on voit les fichiers images ...

>La notice je l'ai eu lors de la lecture d'un répertoire (que j'avais préalablement autorisé => picmanager)

j'ai recorrigé sur le labo pour la notice ... à retester ...

**Comment by previnfo** [comment]
Sur labo:
(1) Dès que l'on essaye d'autoriser on a cette Notice: Undefined variable: filesearch in /home/users/i/infocapagde/www/NPDS/labo/modules/f-manager/f-manager.php on line 772
(2) puis dans le répertoire (autorisé)   Notice: Undefined index: gene-img in /home/users/i/infocapagde/www/NPDS/labo/modules/f-manager/pic-manager.php on line 325

=> Pas d'affichage d'image

**Comment by jipexu** [comment]
> (1) Dès que l'on essaye d'autoriser un repertoire (exemple: images/forum/avatars) on a cette Notice: Undefined variable: filesearch in /home/users/i/infocapagde/www/NPDS/labo/modules/f-manager/f-manager.php on line 772

fixé (il semble bien qu'il manquait un break ....)

pour la 2 ca semble beaucoup moins drôle .... mais il semble que ce soit lié à ce que l'on met dans le champ cache ... du formulaire ?....

**Comment by jipexu** [comment]
attend je ne comprend pas tu me parle de quel erreur ?
sur le labo je sais pourquoi on a cette erreur ...
(2) puis dans le répertoire autorisé (avatars) Notice: Undefined index: gene-img in /home/users/i/infocapagde/www/NPDS/labo/modules/f-manager/pic-manager.php on line 325 ...

toi tu as donc deux erreurs différentes ? ?

**Comment by jipexu** [comment]
>Je n'ai pas la notice
@Jireck-npds  tu as modifier grab_globals.php ?

**Comment by previnfo** [comment]
Oui je n'avais pas la même ligne commentée pour le report d'erreurs grab_globals.php
Néanmoins en me mettant la même chose que labo cela ne change rien (pour moi), j'ai toujours les mêmes notices.

**Comment by Jireck-npds** [comment]
> Je n'ai pas la notice
> @Jireck-npds tu as modifier grab_globals.php ?

Non ! Toutes les remarques que je fais en retour de test sont sans modif juste du parametrage standard

**Comment by Jireck-npds** [comment]
> je ne suis pas spécialiste du file manager mais il me semble que ce comportement est normal
> * si il n'y a pas d'autorisation picmanager (le petit fichier)  on ne voit que les répertoires
> * si il y a autorisation on voit les fichiers images ...

Il est dommage que le compte admin créé lors de l'install n'est pas d'autorisation un minimum
et faire une petite notification avec les droits et un lien vers l'aide 
![image](https://user-images.githubusercontent.com/16939826/47547574-571ef080-d8f6-11e8-8463-cd84e5fc4836.png)

**Comment by jipexu** [comment]
>Oui moi aussi je n'avais pas la même ligne commentée pour le report d'erreurs grab_globals.php
Néanmoins en me mettant la même chose que labo cela ne change rien (pour moi), j'ai toujours les mêmes notices.

>Petit Rectificatif: j'ai avec la précédente notice (...on line 86) bien l'affichage des images .... (il m'a fallu scrooller un moment cette répétition de même notice pour les voir en bas de page)

est ce que tu peux reproduire l'erreur de la ligne 86 sur le labo ???

**Comment by jipexu** [comment]
je ne vois pas le rapport avec l'install et le compte admin ...?
pour l'instant il n'existe que deux dossiers dans l'archive qui embarque un pic-manager.txt
celui de l'utilisateur par defaut
users_private/user/pic-manager.txt
et
celui de la matrice des groupes
modules/groupe/matrice/images_groupe/pic-manager.txt

oui on a pas d'aide : peut être rajouter un onglet avec lien sur l'aide ...

**Comment by jipexu** [comment]
@previnfo mais tu dois toujours avoir (et ce que sur le dossier avatar)
 Notice: Undefined index: gene-img in /home/users/i/infocapagde/www/NPDS/labo/modules/f-manager/pic-manager.php on line 325 ... ??

**Comment by previnfo** [comment]
Oui exact 
la cause => ma ligne commentée pour le report d'erreurs grab_globals.php était revenu par défaut.... (?) 
J'ai remis les mêmes que labo & oui la notice revient .

**Comment by jipexu** [comment]
>Pour info j'avais deja fait cette fonction pour TD-Gal et dans certains parties du main integré.

oui c'est pour cette raison que j'ai écrit 

.... qu'on avait fait évolué pour le support png ...

**Comment by jipexu** [comment]
>tu as pas l'onglet ou un lien vers configurer son pic-manager (il est admin il peut).
Tu as l'onglet et ton pic-manager est fait en meme temps que le premier compte admin.

comprend pas ...

**Comment by Jireck-npds** [comment]
Je reformule : 
A quoi sert d'avoir un onglet "image manager" si c'est la même chose que file manager ?

Donc prenons un peu de hauteur.
Le Compte Admin de l'installation est par défaut le plus élevé privilège avant avec ce compte créer d'autres comptes admin avec un droit superadmin. il doit donc avoir toutes les fonctions actives ou activable facilement.

Avec cette information ci-dessus, pourquoi ne pas avoir les choses suivantes : 
1, "image manager" activé en même temps que la déclaration du compte admin dans l'installation.
2, avoir l'onglet mais qui pour les admins, qui pointe soit vers la gestion / création de "image manager" soit c'est actif donc comme actuel.

**Comment by jipexu** [comment]
image manager et file manager c'est pas la même chose (actuellement)
- dans file manager tu as toutes les fonctions relatives aux dossiers et fichiers (y compris celle d'autoriser le pic manager pour un dossier ...)
dans image manager tu n'as que la navigation entre les répertoires et si ceux ci ont le pic manager activé alors tu vois toutes tes images et que les images  ...
donc y'a quand même une différence non ?


>Donc prenons un peu de hauteur.
Le Compte Admin de l'installation est par défaut le plus élevé privilège avant avec ce compte créer d'autres comptes admin avec un droit superadmin. il doit donc avoir toutes les fonctions actives ou activable facilement.

>Avec cette information ci-dessus, pourquoi ne pas avoir les choses suivantes :
1, "image manager" activé en même temps que la déclaration du compte admin dans l'installation.
2, avoir l'onglet mais qui pour les admins, qui pointe soit vers la gestion / création de "image manager" soit c'est actif donc comme actuel.

... La tu as pris beaucoup trop de hauteur pour moi ...

Je ne vois toujours pas ce que vient faire le ou les admins la dedans ... 
tu veux que tous les dossier est une autorisation pour pic manager ????

**Comment by Jireck-npds** [comment]
Pour redescendre un admin ( et surtout le premier. seul compte admin) doit avoir tous les droits.
Il a tous les droits sur File manager et en changeant d'onglet on a plus rien (puisque pas actif)
Cela me semble pas logique. voila la logique pour les admins. 

Je suggere que le pic manager soit au moins activé, pour le compte admin, sur le repertoire images et sous rep
