### ISSUE TITLE
Valeur par défaut des fins de publication

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#379]
Il y a une erreur dans la conception d'un nouvelle article en admin 
La date de fin de publication a une année de retard
![image](https://user-images.githubusercontent.com/16939826/47429165-c5986d00-d795-11e8-8ab1-b8baf162a024.png)

**Comment by Jireck-npds** [comment]
Effectivement, mais bon la projection sur 99 ans... me laisse perplexe,10, 25 ans ou 50 c'est deja bien 
sinon il faut taper la date à la main ou cliquer plein de fois ...

**Comment by previnfo** [comment]
Oui, mais il parait qu'on vivra plus.... longtemps .... !? (sourire !)
En réalité, => cette projection sur 99 années perdure dans le temps, car elle avait aussi été relevée  dans les versions précédentes de NPDS..   ;-)

**Comment by jipexu** [comment]
oui ça toujours été ces valeurs ... tu proposes quelle valeur par defaut ??

**Comment by Jireck-npds** [comment]
5 ou 10 mais c'est plus prev qui faut voir ...
mon plus vieux site à 6-7 ans

**Comment by previnfo** [comment]
10 years =>  Oui cela me semble correct... !! 
Mais au juste, n'ayant pas eu encore l'occasion d'atteindre cette deadline ... , loin vers l'infini & au-delà de ces 99 années..., _(autre que la fin de publication)_ qu'advient il de nos chers articles ? (archive ou erase) ? ;-)
