### ISSUE TITLE
native-font stack and tinyMCE fontselect

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#380]
Il y a toujours un probleme de traduction pour les font dans l'editeur

![image](https://user-images.githubusercontent.com/16939826/47429448-be259380-d796-11e8-8fd9-65697354b092.png)

**Comment by jipexu** [comment]
ce n'est pas un problème de traduction...
BS utilise https://getbootstrap.com/docs/4.1/content/reboot/#native-font-stack
et comme Tiny met par défaut la valeur du font family du body alors on a droit a cet affichage c'est donc un manque de finesse tiny pour son affichage du font utilisé par le body .... j'ai pas vu d'issue dans tiny a ce sujet (met c'est vrai qu'il y plus de 900 issues ouvertes ... et 2800 fermées )

**Comment by jipexu** [comment]
https://github.com/tinymce/tinymce/issues/4648
