### ISSUE TITLE
Interface admin groupe

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#381]
Pourquoi on a une image de NPDS lors de la creation d'un groupe alors que cela n'as rien a voir

![image](https://user-images.githubusercontent.com/16939826/47431106-705f5a00-d79b-11e8-8fff-0ea0ecce29c4.png)

**Comment by Jireck-npds** [comment]
Autre question pratique
Pourquoi on a pas les options d'activer les options du groupes avant d'avoir au moins une personne dedans ? 
Perso, j'aime bien tout créer part avance puis ajouter les utilisateurs tous a la fois. l'objectif de cette manip étant que les utilisateurs voient tout d'un coup et pas il truc au fur et a mesure.
Puis si des gens fonctionnent comme moi ils vont se demander où sont les boutons
![image](https://user-images.githubusercontent.com/16939826/47431600-79046000-d79c-11e8-92a8-fd6d26493f8b.png)

**Comment by jipexu** [comment]
>>Pourquoi on a une image de NPDS lors de la creation d'un groupe alors que cela n'as rien a voir
c'est une image par defaut de la matrice
qu'est ce que tu proposes ?

**Comment by jipexu** [comment]
>Autre question pratique
Pourquoi on a pas les options d'activer les options du groupes avant d'avoir au moins une personne dedans ?
Perso, j'aime bien tout créer part avance puis ajouter les utilisateurs tous a la fois. l'objectif de cette manip étant que les utilisateurs voient tout d'un coup et pas il truc au fur et a mesure.
Puis si des gens fonctionnent comme moi ils vont se demander où sont les boutons

c'est juste une autre logique du process ...  un groupe > des membres > puis des fonctions

**Comment by Jireck-npds** [comment]
Pour l'image, Ne rien mettre c'est bien.
Si on met une image, on (webmaster du site) doit pouvoir la choisir comme ca visuellement c'est plus simple si on a beaucoup de groupe.

Pour la logique du process c'est pas ma (la) logique.  dans un process ce n'est pas parce que personne ne l'utilise que tu ne peux pas avoir accès aux fonctions. et ça empêche (déformation professionnel) d'avoir un impact utilisateur.

Donc dans la logique : Des que tu crée un groupe, tu dois pouvoir créer tout ce que tu veux donc les boutons pour les fonctions. les fonctions sont lié au groupe et non aux membres.
J'ai pas verifier mais si tu crée tous pour un groupe (minisite,chat,etc...) et que tu vire tous les membres tu ne peux plus les supprimer les chats, ministite etc .. lié aux groupes ? obligé de remettre un membre ?

Je me demande aussi pourquoi tout l'espace de la colonne (largeur) n'est pas utilisé
![image](https://user-images.githubusercontent.com/16939826/47452056-8ab02c80-d7c9-11e8-8a15-34ad999f9c34.png)

**Comment by jipexu** [comment]
>Pour l'image, Ne rien mettre c'est bien.
Si on met une image, on (webmaster du site) doit pouvoir la choisir comme ca visuellement c'est plus simple si on a beaucoup de groupe.

oui ce serait mieux mais tant qu'on a pas implémenté une interface pour le choix de l'image du groupe alors je pense que cette solution est la plus évolué .. car elle permet au moins de voir qu'on peut avoir une image pour le groupe ( même si  bien entendu elle amène la question comment on fait ...)
(c'est d'ailleurs la même que celle qu'on trouve pour les modules)

**Comment by Jireck-npds** [comment]
donc
Pour l'image, Ne rien mettre c'est bien.
Mais fait comme tu pense

**Comment by Jireck-npds** [comment]
Change l'image alors ...
Met juste des cube et pas le "workspace for npds"
Broutille mais cela porte à confusion
