### ISSUE TITLE
Question theme

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#387]
Bonjour,

Dans la personnalisation d'un theme comment changer simplement les icones (font) des forums je parle des : 
 = Les nouvelles contributions depuis votre dernière visite.
 = Plus de 10 Contributions
 = Aucune nouvelle contribution depuis votre dernière visite.
 = Plus de 10 Contributions
 = Ce sujet est verrouillé : il ne peut accueillir aucune nouvelle contribution.
on est obligé de changer dans le code ?

**Comment by jipexu** [comment]
....désolé hélas oui .... avec les images on avait deux possibilité avec les fonts pour l'instant on en a qu'une ....

**Comment by Jireck-npds** [comment]
on parait pas surcharger la css avec un id pour prendre autre chose...
Je regarderais plus en profondeur
