### ISSUE TITLE
Problémé avec les accents

### ISSUE THREAD

**Issue by Gery59** [npds/npds_dune#39]
Bonjour
Je viens d’installer la V16 en parallèle avec mon site ancien qui fonctionne.
J'ai donc la même base de donnée.
Avec un peut de codage sur le sql il est vrais.
Tout fonctionne parfaitement.
Par contre il y a sur la V16 un problème avec les accents, pas que sur le forum..
Si j'écris un texte sur la V16, par exemple sur le forum, je retrouve la même erreurs sur le site ancien.
L'inverse n'est évidemment pas vrais.

Cordialement

Géry.

**Comment by jipexu** [comment]
Sur une V16 quel est le  type de problème que tu rencontre avec tes accents? Quel sont les paramètres d'encodage de ton site de ta base? Tu parle d'un problème avec Rev 16 qui prend les données dans une  base déjà existante ??

**Comment by Gery59** [comment]
Bonjour,

Merci pour la réponse.
En effet, j'ai fusionné les deux bases de données, la ReV13 et la V16 
pour continuer à faire fonctionner l'ancien site de façon qu'il n'y est 
pas d’interruption le jour ou je basculerais sur la V16. J'ai fais sur 
NPDS un petit topo...
Hors sur une partie du site les accents ne passent pas, surement un 
problème d'encodage?
En partie sur le forum, les Boxs, les chat...
J'avais d'ailleurs constaté le même problème avec la V16 avant de 
modifier la BdD.
De même sur le site NPDS je vois que sur le forum certains ont le même 
problème...
Pour vous permettre de voir.
Mon ancien site en ReV13:
http://horizon-genfit.mgcl.fr/index.php?op=edito
Le nouveau en V16 (Même base de donnée)
http://horizon-beta.mgcl.fr/index.php?op=edito
Je précise que si j'écris sur l'ancien site pas de problème, si j'écris 
sur la V16 le problème d'accent se constate aussi sur la ReV13

Cordialement

Géry

**Comment by jipexu** [comment]
Merci de tes retours oui ces problèmes peuvent exister .. mais ce qu'il faut savoir c'est si avec des données homogènes ont a des problèmes .. En principe avec des données homogènes tu ne dois pas avoir de problème... Quel encodage as tu choisi pour ton site (a t il changé ?) ... Parfois la seule solution est de reprendre la bd pour corriger définitivement ... Tien moi au courant car beaucoup rencontreront ce problème ... et je ne peux que conseiller de passer les sites en utf8 ( ce qui engendre forcément du travail sur la bd ...)

**Comment by jipexu** [comment]
tu dois au plus vite stabiliser (choisir définitivement==> utf8) car actuellement tu as une bd et deux sites un avec un charset en iso l'autre avec un charset en utf8 ... donc logiquement avec cette configuration tes formulaires envoient à ta base des données encodé en utf8 (nouveau site) et en iso (ancien site ...)
- dans le nouveau site tu dois aussi affiner ta variable locale pour que tes dates (de post par exemple février) soit encodé correctement...
- et ensuite nettoyer ta base (notamment les titres des posts des articles etc ....)

**Comment by Gery59** [comment]
Donc si j'ai bien compris, je dois modifier l'ancien site pour qu'il 
envoie en utf8, mais ou?

**Comment by jipexu** [comment]
OUI metatag dans l'admin !!

**Comment by Gery59** [comment]
Merci de la réponse, je venais juste de le faire mais du coup j'ai un 
problème d'accent sur l'ancien site, sauf si je corrige.
Mais je ne vais pas tout corriger????

Bonne soirée

Géry
