### ISSUE TITLE
Changer l'ordre des rubriques

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#392]
Hello,

Apres création d'une catégorie dans les rubriques, on me demande de changer l'ordre.

![image](https://user-images.githubusercontent.com/16939826/48063565-bb2e9800-e1c5-11e8-9d0d-e5b83213f5d5.png)

Me basant sur l'intervalle et l'experience des groupes, je decide de mettre 10

![image](https://user-images.githubusercontent.com/16939826/48063588-d4374900-e1c5-11e8-9335-c9adf9992f8c.png)
Erreur me précisant je suppose de **1 à 4** ==> Cela me semble bien peut ... erreur JS ou autre...

Et en mettant 1 J'ai 
![image](https://user-images.githubusercontent.com/16939826/48063689-1cef0200-e1c6-11e8-8c47-0e04ce0f9715.png)

Ce qui est pas normal du tout

**Comment by Jireck-npds** [comment]
Pareil pour les sous rubrique
![image](https://user-images.githubusercontent.com/16939826/48063947-c8985200-e1c6-11e8-9fb6-fdb8dc83c3f9.png)

![image](https://user-images.githubusercontent.com/16939826/48063982-dea61280-e1c6-11e8-889e-9fa7510c1448.png)

**Comment by Jireck-npds** [comment]
Surtout que les valeurs par defaut ne sont pas valide
![image](https://user-images.githubusercontent.com/16939826/48064050-08f7d000-e1c7-11e8-9102-2b536bfa060f.png)

**Comment by jipexu** [comment]
il semble qu'on est juste un petit problème avec les valeurs par défaut non ? le reste fonctionne il me semble ..
si tu as 3 item à réordonner mettre un 10 n'est pas possible car le contrôle est dynamique (en fonction du nombre d'élément à réordonner ...)

**Comment by jipexu** [comment]
ah oui et encore ..  le fait que la valeur par default ne soit pas dans les clous oblige à mettre des valeurs cohérentes .... ou alors on met 0 en default

**Comment by Jireck-npds** [comment]
Donc pour moi le systeme est pas bon ...

Pourquoi : 
Generalement ces ID servent a classer l'ordre et sont afficher suivant l'ordre donné.

Le fait de : 
- ne pas mettre l'ID desiré empeche l'anticipation de création d'autres categories ou sous-categorie
- oblige à modifier à chaque fois les Id 
- Oblige à modifier le N° ID de "divers" et "press papier"
- donne un ID faux pour  "divers" et "press papier"

Bref sous prétexte de contrôle (normalement non obligatoire) on oblige des manipulations. sutour que cela ne change rien dans la base

Solution proposé : 
- Laisser un Panel ID en 999X pour  "divers" et "press papier" (toujours dernier sauf changement explicite)
-  laisser le choix des ID
- Indiqué le range d'ID  et contrôler les doublons d'ID

Gain : Flexibilité, compréhension, modularité

**Comment by jipexu** [comment]
http://www.npds.org/viewtopic.php?topic=26710&forum=4
