### ISSUE TITLE
Amelioration éphéméride

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#398]
En liaison avec [226](https://github.com/npds/npds_dune/issues/226) et  [396](https://github.com/npds/npds_dune/issues/396)

Pouvoir avoir un tableau d'état : 
 - éphéméride | Jour | Mois | Edit | delete

**Comment by jipexu** [comment]
bof .... le tableau risque d'être vraiment très long !!!
tableau ... pagination du tableau etc ...

**Comment by jipexu** [comment]
pas suffisant ...
si tu commence ton ephemeride a la naissance du christ ca te fera 2019x30=60570 x par le nombre d'évènement par jours.. enfin tout ceci pour dire que on ne peut pas faire une requete simple et qu'il faut un tableau avec pagination ... réfléchir ... enfin du boulot quoi
