### ISSUE TITLE
Forum admin config

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#412]
Heelo 

J'ai pas tester mais 255 caracteres c'est pas un peu beaucoup pour un role ? 
pas tester mais au niveau affichage ça donne quoi ? a moins que ce soit pas afficher...

![image](https://user-images.githubusercontent.com/16939826/48200612-f5cc3800-e35f-11e8-97e1-6f43474695e3.png)

**Comment by jipexu** [comment]
255 car ne seront vraiment pas de trop si on veux implémenté le multilangue .. donc on laisse ...
