### ISSUE TITLE
module gestion installation

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#417]
J'upload un module de ma fabrication
Je vais dans gestion
Je veux valide mon module 
![image](https://user-images.githubusercontent.com/16939826/48302257-c7cf2b00-e4fa-11e8-80df-326fd15ae9a6.png)
et j'obtiens ca 
![image](https://user-images.githubusercontent.com/16939826/48302264-d7e70a80-e4fa-11e8-91e9-9d373f91bb7b.png)

C'est con ...
de plus sur la premiere image il faudrait rajouter les icones des modules au lieu d'une piece de puzzle et aussi question : 
Pourquoi il n'y a pas les modules
![image](https://user-images.githubusercontent.com/16939826/48302282-25637780-e4fb-11e8-9af5-b09f0576efbf.png)

En signifiant qu'il sont integré ?

**Comment by jipexu** [comment]
- la piece du puzzle c'est quand le module n'a pas d'icône ...
il n'y a pas les modules qui n'ont pas d'interface pour leur admin ....

**Comment by Jireck-npds** [comment]
Il faut donc rajouter une icone dans chaque module incorporé de base 
![image](https://user-images.githubusercontent.com/16939826/48702991-b967ca00-ebf2-11e8-8aca-28e9eabe5086.png)

Pécadille mais bien je pense

**Comment by Jireck-npds** [comment]
dans font awesome on a 
page time `<i class="fas fa-stopwatch"></i>`
Push `<i class="fas fa-project-diagram"></i>`
Marque ta page `<i class="fas fa-book-open"></i>` ou `<i class="far fa-bookmark"></i>`
Contact `<i class="fas fa-address-card"></i>`
blocnote `<i class="far fa-sticky-note"></i>`

**Comment by jipexu** [comment]
==> fait pour blocnote, marquetapage, et pagetime

je reste sur des ressources images pour ce secteur de l'iconographie (plus de choix et cohérent avec le reste de l'admin )  pour infos pour l'instant on ne dispose pas des classes fas far de fontawesome car on est toujours en version 4 .... et ces ressources proviennent de la version 5 ...)
