### ISSUE TITLE
harmonisation des contrôles  (js php) des adresses mail

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#421]
Quand on écrit une **critique**, le javascript valide l'@mail sans extention de domain
![image](https://user-images.githubusercontent.com/16939826/48399174-3393dc80-e723-11e8-9cab-7bcffad43bb9.png)

Par contre la dévalide en previsualisation
![image](https://user-images.githubusercontent.com/16939826/48399202-4c9c8d80-e723-11e8-8b47-f88b5461f1e8.png)

**Comment by jipexu** [comment]
oui faudrait harmoniser les expression régulière de contrôle ...
( on en a déjà parlé ... notre contrôle js est dans l'absolu  plus juste que notre contrôle php ...)
