### ISSUE TITLE
(Amélioration fonction mail php) Option SPF & DKIM,

### ISSUE THREAD

**Issue by previnfo** [npds/npds_dune#423]
**Objectif** :  trouver une solution pour "signer" nos mailings & ainsi éviter de retrouver les fonctions mails de NPDS **spammées** par les serveurs clients. 

**Intro** :  c'est pratiquement systématique pour des sites communautaires, là ou le nombre de membres commence à grossir / ou pour des sites marchands, avec les envoies de xxx newsletters .... 
Si nos hébergements se trouvent sur des serveurs "**mutualisés**" (même adresse ip du serveur),  ....  la conséquence du nombre d'envois fait qu'on se retrouve très souvent black-listé/spammé par les messageries clients comme free & bien d'autres ...  Et à moins d'avoir un serveur dédié, car les serveurs mutualisés sont majoritairement dépourvus dans leur cpanel ou plesk de fonctionnalités comme les inclusions dans le DNS de keys SPF & DKIM.

**Les conséquences sont particulièrement nuisibles**, "spam" des fonctionnalités NPDS utilisant le mail 'abonnements/lost mot de passe/newsletter .... .'   => pour une certaine partie de nos membres  = bien souvent à une grosse faiblesse dans les capacité de communications

J'avais déjà eu à étudier ce PB avec NPDS sur mon premier hébergeur, je m'y replonge car malheureusement c'est de nouveau le cas avec le présent serveur.  

**Proposition** :  Une éventuelle solution serait d'incorporer ce type de script "**phpmailer**" en option de config dans "NPDS" , J'imagine que ce serait un grand ++

=> le site officiel https://github.com/PHPMailer/PHPMailer 
=> Expliqué => https://caillaud.fr/phpmailer-envoyer-mails-signes-dkim/ 
=> Les keys = https://dkimcore.org/tools/keys.html 

Bon je vais essayer de voir ses "possibilités" en bricolant quelques codes avec  mon domain name, mais pas certain d'y arriver ... lol

**Comment by Jireck-npds** [comment]
Pas plus simple de baisser la priorité ? 
`$advance="X-Priority: 2\n";`

**Comment by previnfo** [comment]
les niveaux 1 2 3 4 ou 5 de  $advance="X-Priority:  n'influenceront qu'une interprétation du logiciel client par exemple des icônes type /!\  ...    
=> mais ne joue pas de rôle, ni d'influence sur le FAI de (x) clients, qui s’aperçoit / ou vient de tracer l'envoie de multiple messages (**non signés**) par un même **nom de domaine** ou IP ... et cela, quelque soit le niveau de X-Priority.  d'un message.   (Ex cela peut se produire pour la fonction mail abonnement des forums => site communautaire comme npds)

**Comment by Jireck-npds** [comment]
Jamais eu ce problème...
Malgré tout avoir un Niveau de priorité correct (normal) me semble mieux.
Maintenant n'ayant jamais eu ce problème je n'en dirais pas plus

**Comment by Jireck-npds** [comment]
j'ai un gmail : jireck at gmail.com

**Comment by previnfo** [comment]
Merci, 
Je fais le test, mais pour Gmail je n'aurais normalement aucun soucis.

Pour l'instant, c'est free  => http://postmater.free.fr     
leur outil filtre me classe X-ProXaD-SC: state=**SPAM** score=**160**
Il me faudrait avoir un score inférieur à 100 pour ne plus être SPAM.

C'est un PB récurant pour les abonnements des forums avec free. Chez moi cela ne touche que 380 freemembres.

**Comment by previnfo** [comment]
Ben voilou lui aussi

**Comment by Jireck-npds** [comment]
Les pistes à voir sont souvent simple : 
Concordance : nom => adresse mail ( gerant <=> webmaster )
serveur domain :  sv66.ifastnet15.org <=> previnfo.net
Niveau de priorité normal =+> 2 => 3
bizarre le Content-Transfer-Encoding: est 7bit ..
Rajouter peut etre un replyTo avec la meme adresse

**Comment by previnfo** [comment]
Merci pour tes pistes (préalablement investigué / bricolé mes DMARC DKIM SPF directement dans la config DNS du domain sur cpanel)... 
https://www.mail-tester.com/test-itxlt   =  Parfais 10/10

Cela me semble un peu plus complexe, car le nom d'un mail n'importe peu, c'est l'ensemble des adresses via le nom de domaine (previnfo) comme d'autres noms de domaine que j'ai sur ce serveur qui est touché par le score "spam " de 150.  Donc, la source du pb cible est plus probablement du côté serveur DNS "sv66.ifastnet15.org" qui lui-même est mutualisé (partageant xxx domaines)...   

Maintenant, même si j'ai 10/10 sur tous les testeurs de mailing & que mon nom de domaine semble aussi être clean. Mon investigation sur les causes du spamming me pousse aussi a dire que dans nos pratiques (previnfo/npds) nous ne sommes pas exsangue de tout reproche non plus.  

En effet, le systeme NPDS actuel peut rapidement être considéré comme spammeur par les nouveaux Outils d'analyse de délivrabilité emails.   Plus précisément le wrong mailling list te trace beaucoup plus vite comme un spammeur & influence défavorablement ton score de HAM à SPAM..   (Une faiblesse que l'on peut avoir sous NPDS avec le temps)

Exemple, au bout de dix ans sur NPDS (prev) avec 7000 membres qui se sont enregistrés, pour certain avec des emails bidons* ou devenus obsolètes, les x abonnements (forums/article/... ) font que sans avertissement le système continue toujours (sous ton nom de domaine) à envoyer en erreur du Wrong mailing address...  

En sus des améliorations de type phpmailer (DMARC DKIM ... ) un outil pour authentifier en mesure de trier les potentiels envois de mails serait aussi + plus ...  

(*) Pour l’instant le seul outil de vérification email sur NPDS, est celui du Control de la syntaxe...  
J'ai vu qu'il existait des bouts de code PHP pour aussi vérifier la délivrabilité, ceci dit, cela ne pourrait être qu'a l'enregistrement de nouveau membre (pour les warriors du php étendre cela sur une vérification du mailing avant envoie).  

https://atranchant.developpez.com/code/validation/

**Comment by Jireck-npds** [comment]
Je me suis jamais penché sur ce probleme de mail n'ayant jamais eu ce probleme mais je le comprends.

Il y a deux problèmes : 
1) le problème d'envoie de mail qui passe en spam
2) un problème de remédiation des informations de tes membres.

Pour le premier, faut que je me penche dessus sans pouvoir faire de tests. je pense que jpb est comme moi.

Pour le second, il faut il me semble, developper un module en 2 parties : la premiere pour du reporting en tant qu'admin et une deuxieme pour "demande aux membres d'updater certains champs profil.

**Comment by previnfo** [comment]
Un gros taf de différents correctifs (DNS)  DKIM DMARC SPF (Npds) subscribe  ....  -- mais aussi => des messages aux supports Free / Gmail qui commencent à payer,  (au moins pour => free) ...   **X-ProXaD-SC: state=HAM score=10** / (Pas fini) Car toujours en spam pour Gmail. (Rappel un score au-dessus de 100 = spammeur). 

Du moins je me fais plaisir en pensant que j'y suis pour quelque chose. La réalité est peut être ailleurs LOL ...

Ceci dit, oui Jireck / jpb /... ,  **si on arrive a trouver/bricoler des astuces pour tenter de renforcer la sécurité de nos mailing serait un gros + .**  

Ce fut très instructif pour moi, mais c'est un monde obscur, un véritablement tord cerveau pour un bricoleur du dimanche comme moi. J'imagine fortement que le quidam puisse rapidement ce décourager & jeter rapidement l’éponge. 

@+

**Comment by jipexu** [comment]
lors de  l'entrée d'adresse email on pourrait déjà facilement contrôler si le domaine existe et si il est de type MX  et dans la foulée essayer d'établir une connection ...

avec ca on éliminerait un bon nombre d'adresse fantaisiste .... ce serait une première étape ! importante à mon sens ...

**Comment by Jireck-npds** [comment]
En état du développement, je dirais que cela est à mettre dans le sujet amélioration pour un patch après.
afin de finir ce développement.

Il faut vraiment, pour moi, différencier : 
 Les bug a corriger dans cette version
Les améliorations pour un patch juste après.

ce qui nous donne des steps d’amélioration.

Mais continuons a discuter pour avoir une solution / implementation...

Le controle du serveur Mx est déjà une bonne solution.

**Comment by previnfo** [comment]
Oui, le contrôle du serveur Mx est une très bonne solution pour les domaines "false" dès l'enregistrement. 

Elle reste toutefois **inopérante** face aux adresses emails temporaires/anonymes de types Yopmail.com (qui ont un Mx temporaire), ainsi que d'autres emails (de domaine pro ou perso) qui par l'usure du temps, de gré ou mal gré finissent par être Down !!!   // <Ce qui n’empêche pas aux membres concernés de toujours pouvoir se connecter comme d'être actif (sans se soucier d'une quelconque validité de leurs emails) .

Il faudrait effectivement un outil "admin" qui nous permettrait au minimum de tracer ou d'être alertés de ces emails 'Down'  (**admin** & éventuellement user).  Afin de prendre des mesures pour éviter que le système de notification NPDS  / newsletters / .... insiste à polluer les mêmes fails (comme un vilain petit spammeur)

**Comment by Jireck-npds** [comment]
Faut peut être aussi checker les A et les MX

**Comment by jipexu** [comment]
Que veux tu dire ? A quoi servirait le controle du A dans ce cas la ? La fonction check le MX ...

**Comment by jipexu** [comment]
ok implémenté avec PHPmailer en support : 
- support pour smtp(s) avec ou sans authentification et cryptage ou non
- génération de DKIM automatique
- par contre pas de solution pour SPF si ce n'est un controle par le webmaster pour savoir si il existe et est correct (ce que beaucoup d'hébergeur néglige de s'occuper sans demande express ...)
