### ISSUE TITLE
Les fichiers de configuration

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#427]
Hello, 
Il serait bien, si possible d'avoir une différence entre l'édition de fichier et la création suivant le modele.

![image](https://user-images.githubusercontent.com/16939826/48617244-2f232a00-e996-11e8-9e0a-ad131d7fafb3.png)

Image avec les fichiers par defaut

**Comment by jipexu** [comment]
euh ?... où peux tu créer un fichier dans cette interface ?...

**Comment by Jireck-npds** [comment]
Si on prends l'exemple de body_onload.inc, le fichier n'existe pas et demande si on veux le créer suivant le modèle.
C'est là où il est préférable de mettre une différence entre les fichier actif donc éditable.
Et le fichier non actif donc à créer par défaut. 
On aurait un truc du genre : 
header_head ==> icone editer + "editer le fichier" en popup ==> click ==> page edition du fichier
body_onload ==> Icone [ + ]  + "Créer le fichier"  ==> click ==> page Créer le fichier en utilisant le modèle ? oui / non 

Comme cela on a aussi les fichiers actif ou pas .
