### ISSUE TITLE
Tarte au citron

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#428]
Pourquoi tu n'as pas inclue tarte au citron en fichier externe ?
Genre : 
include (lib/rgpd/rgpd-head.php);
include (lib/rgpd/rgpd-foot.php);
// dans l'exemple le fichier rgpd-xxx.php contient tout pour son appel

Comme ca, si on veux dans le futur changé de script, ou si on veux mettre un autre script de rgpd en tant que webmaster, on a pas a tout modifier.
valable aussi si on veux parametrer facilement tarte au citron 
valable encore pour aider dans les forums sur le sujet
valable aussi pour la doc.

Mais c'est vous qui voyez

**Comment by Jireck-npds** [comment]
> * quand au changement d'outil c'est plus compliqué car il faut de fait aussi modifier certain metamots qui génèrent du html par exemple les meta-mots vidéo  ...

Je ne comprends pas

**Comment by jipexu** [comment]
ps : avant de choisir tarteaucitron j'avais regardé 3 ou 4 autres outils ... et la patisserie avait remporté le concours haut la main ...

**Comment by Jireck-npds** [comment]
Je ne suis pas convaincu pour ma part...
Surtout par ce que cela reste trop visible en bas a droite
mais bon

**Comment by previnfo** [comment]
Pourtant, c'est un des seuls qui respecte le mieux ce qui ait demandé par le Règlement général sur la protection des données.... 
=> (a) Notamment, laisser la possibilité à l'utilisateur de modifier/gérer **à tout moment** ses choix de confidentialités. 
C'est vrai que beaucoup de sites sont encore en dehors de clous ou très flou sur ce point (a) en utilisant un simple/unique bandeau d'acceptation à la première connexion d'un utilisateur, mais (par obligation RGPD) ils commencent step by step à 's'y mettre.  => Regarde un similaire sur Eurosport.fr .. 

Moi je trouve TAC très bien, et effectivement tu peux configurer le retrait de la console en bas à droite... Mais là on ne respecte plus ce que précise de nouveau la CNIL "...l'internaute doit pouvoir refuser les cookies à tout moment ..."

**Comment by Jireck-npds** [comment]
Je sais pas ... pas de doc et par defaut ca apparait tout le temps
FAudrait que je me penche dessus.
C'est aussi pour cela que je voulais que ce soit en exterieur pour avoir un fichier conf et 2 fichiers d'appel.
