### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by BeWorld2018** [npds/npds_dune#440]
Bonjour,
Je suis en train de tester la version 16 (beta 3)
Dans l'aAdministration / Préférences / Informations générales du site 
Impossible de "Sauver les modifications", le bouton ne semble pas fonctionner.
Pouvez-vous vérifier ?

**Comment by Jireck-npds** [comment]
Bonjour 
Je pense que tu ne peux pas sauver car certaines informations obligatoires ne sont pas rempli et par contre sont dans les catégories repliés donc pas visible.

J'avais déjà remonté le problème que certaines données dans les preferences ne sont pas juste et qu'on était obligé de les modifier alors qu'elles sont de base.

En bref deplie toutes les categories dans les preferences et regardes s'il y en a en rouge qui sont incorrect.
par exemple, le mail de je ne sais plus quel champs est pas bon

**Comment by BeWorld2018** [comment]
Bj,
Merci en effet c'était bien ca....

Autre question :-)
Existe -til des modules ou script sql pour Mettre à jour des bases des anciennes version de Revolution ? NPDS ? (même avant la version 13 ?) merci

**Comment by Jireck-npds** [comment]
Le script de mise a jour de la version 13 a la derniere est pas encore réalisé (in progress).

Pour mettre a jour les anciens sites vers la nouvelle version, il n'y a pas de script rattrappant les delta.
Il faut : 
- déterminer sa version
- Regarder les differentes vesion jusqu'a la 13
- telecharger les diverses version en les appliquant une a une en suivant les procedures indiqué dans chaque version.

Generalement, il faut uploader la nouvelle version puis lancer le script de migration (par exemple http://monsite.com/updated.php) puis valider les preferences.
il faut sauvegarder la bdd avant chaque update (dump de la base)

**Comment by previnfo** [comment]
Bonjour,

Comme le dit parfaitement Jireck,  
En l’état actuel : _pas 'encore' de script V13 =>V16_
(1) il vous faut UP votre "old" NPDS jusqu'à la V13. 
(2) Puis installer indépendamment la nouvelle V16 (beta3) et, instruire via Phpmyadmin ou autre, les data de votre "ancienne" bdd dans la nouvelle base V16 (_en comparant / ajoutant (& ajustant) certaines tables qui ont été améliorés_) 

Cela est un peu fastidieux, mais 'parfaitement' fonctionnel ...
@+

**Comment by jipexu** [comment]
@BeWorld2018 

> Merci en effet c'était bien ca....

est ce qu'il s'agissait des champs ??
Adresse E-mail de l'administrateur
Adresse E-mail où envoyer le message
Compte E-mail (Provenance)

et avec quelle erreur ?

**Comment by BeWorld2018** [comment]
Compte E-mail (Provenance)

Aucune erreur, à parti si on ouvres l'onglet qui va bien, on voit le champs rouge.
