### ISSUE TITLE
Image module core

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#449]
Bonjour,
En regardant le code modifié, je vois 
`      if ($ibid=theme_image("modules/add.gif")) {$add=$ibid;} else {$add="modules/marquetapage/add.gif";}
      if ($ibid=theme_image("modules/addj.gif")) {$addj=$ibid;} else {$addj="modules/marquetapage/addj.gif";}`

Qui me souleve un question : 
Pourquoi ne pas utiliser les webfont pour les modules qui sont presque dans le core ?

Voila

**Comment by jipexu** [comment]
quel fichier ?

**Comment by Jireck-npds** [comment]
marquetapage
