### ISSUE TITLE
Question | footer.html

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#490]
Bonjour
pourquoi mettre : 
`<script type="text/javascript" src="lib/js/jquery.translate.js"></script>
      <script type="text/javascript" src="lib/js/npds-dicotransl.js"></script>
      <script type="text/javascript">
         //<![CDATA[
         $(document).ready(function(){
            var translator = $('body').translate({lang: "fr", t: dict});
            translator.lang("<?php echo language_iso(1,'',0); ?>");
            $('.plusdecontenu').click(function(){
               var $this = $(this);
               $this.toggleClass('plusdecontenu');
               if($this.hasClass('plusdecontenu')){
                  $this.text(translator.get('Plus de contenu'));
               } else {
                  $this.text(translator.get('Moins de contenu'));
               }
            });
            if (matchMedia) {
               const mq = window.matchMedia("(max-width: 991px)");
               mq.addListener(WidthChange);
               WidthChange(mq);
            }
            function WidthChange(mq) {
               if (mq.matches) {
                  $("#col_LB, #col_RB").removeClass("show")
               } else {
                  $("#col_LB, #col_RB").addClass("show")
               }
            }
         });
         //]]
      </script>`
Dans chauqe footer.html de chaque theme alors que cela depuis si il y a des colonnes .
cela depends donc du pages.php ou plus simplement du $pdst

Cela devrait etre enlever pour etre rajouter soit suivant le $pdst soit dans le fichier footer_after.inc

**Comment by jipexu** [comment]
ce script est spécifique à certains thèmes pas à  tous ..

**Comment by Jireck-npds** [comment]
Peut etre mais au pire il serait mieux dans le include du theme
