### ISSUE TITLE
Ajout des +-@ dans la gestion des mots de passe

### ISSUE THREAD

**Issue by BeWorld2018** [npds/npds_dune#492]
Soir,
LEs +-@ ne sont pas pris en compte comme caractères spéciaux 👍 
ligne 3261 dans mainfile.php

    if (value.search(/[+-@!#$%&^~*_]/) < 0) {

Merci

**Comment by jipexu** [comment]
Yo
Oui j'ai rajouté ça sur les deux lignes concernées ...

en fait on pourrait en rajouter beaucoup d'autres ... ou réécrire l'expression régulière ... car on demande d'avoir au moins un de ces caractères mais au final l'utilisateur ne connait pas ceux que l'on a choisi comme valide ....on ne laisse que peu de possibilités ... ou alors on affiche dans le message ??

**Comment by BeWorld2018** [comment]
oui on pourrait l'écrire, genre une info bulle ou un truc comme ca
