### ISSUE TITLE
[ installation ]Url Site

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#493]
Hello,
Le script ne prends pas en compte les déclarations de port 
![image](https://user-images.githubusercontent.com/16939826/71781385-77544000-2fce-11ea-91d3-2efbf1a7d661.png)

**Comment by Jireck-npds** [comment]
remarque il prends pas non plus http://127.0.0.1

**Comment by jipexu** [comment]
ah ?  faut regarder en principe cela devrait fonctionner ...

**Comment by Jireck-npds** [comment]
pour moi c'est un controle JS pas tres utile mais ..;

**Comment by jipexu** [comment]
pour toi mais si cette variable est mal renseignée elle entraine des dysfonctionnements du portail ... donc pour moi un controle ici est un plus ....

**Comment by jipexu** [comment]
résolu
