### ISSUE TITLE
Question Js

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#494]
Hello 

Pourquoi prism.css et formValidation.min.css sont tout le temps charger par defaut ?

Pourquoi ne pas le mettre dans pages.php

**Comment by jipexu** [comment]
Yo
car il ne serait par exemple pas disponible en cas d'utilisation par des blocs ou des métamots ....
ce serait donc très difficile à identifier .... 
... et on parle de 2k et 10k ...

**Comment by Jireck-npds** [comment]
on parles des js avec

et mettre du code dans des blocs ....

Bref ..
Je les desingrer de mon coté

**Comment by jipexu** [comment]
il n'y a que le js de prism qui est chargé tout le temps.. celui de formvalidation ne l'est que quand on en a besoin ...
