### ISSUE TITLE
Probleme de controle Formulaire

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#495]
Hello,
Lorsque tu crée un nouveau utilisateur au moment de mettre un mot de passe, la validation n'est pas bonne pour les caractères spéciaux : 

OK : +- ! & 

KO : . : ; ,  " ' ( )

et d'autres ...

**Comment by jipexu** [comment]
#492 
pour t'éclairer un peu regarde  ce post .. la validation est bonne pour les "caractères spéciaux" qu'on a choisi ....
le problème en fait quelle est la définition "des caractères spéciaux" ..  ????
 autre que alpha+ponctuation  autre que alphanumérique etc etc 

il faut en choisir plus et documenter plus ...?

**Comment by Jireck-npds** [comment]
generalement il y a tout cela 
https://fr.wikipedia.org/wiki/Aide:Liste_de_caract%C3%A8res_sp%C3%A9ciaux

mais généralement on choisi les plus usité et pas alpha :

· | ’ | “ | ” | « | » | • | – | — | ± | × |  € | & |! | ? |, | ; | :

**Comment by Jireck-npds** [comment]
et les parentheses aussi

**Comment by jipexu** [comment]
ce lien n'est pas d'un grand secours pour notre problème...
dans notre contexte quand on parle de caractères spéciaux (non alpha) ....  on ne parle pas de caractères spéciaux du html .... 
#492
donc il faut rajouter quoi ?

**Comment by Jireck-npds** [comment]
· | ’ | “ | ” | « | » | • | – | — | ± | × | € | & |! | ? |, | ; | :

A partr si certains d'entre eux posent probleme dans les fonctions php qui gere les mot de passe
