### ISSUE TITLE
saisie de longueur mini du mot de passe restrictive

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#496]
Bonjour pourquoi on ne peux pas choisir la valeur qu'on veux dans le champs 
Longueur minimum du mot de passe des utilisateurs

**Comment by jipexu** [comment]
oui c'est à revoir et affiner mais je suis pour des valeurs "encadrées" :  pas de possibilité d'un mot de pass trop court et une limite supérieure...
l'utilisation d'une liste déroulante (à affiner) à l'avantage d'éviter les saisies farfelues ....
Qu'est ce que tu proposes ?

**Comment by Jireck-npds** [comment]
Voila ma vision et ensuite tu décide ce que tu veux.

Il faut rester dans les valeurs connus et standards des mots de passe tout en pensant au site moindre ne cherchant pas de sécu.

la longueur par défaut dépends de la complexité, c'est pour cela que je te rejoins sur le menu déroulant. je verrais un mixte du genre dans le menu avec le nom et les explicatifs lors de la selection : 

Nom          | Longueur        | complexité                                    | consigne
Mini           | 6 caractères    | Aucune                                          | Non Conseillé
Mini +        | 6 caractères    | Alpha Numérique                         | Non Conseillé
Standard    | 8 caractères    | Alpha Numérique                          | Par défaut
Standard + | 10 caractères  | Alpha Numérique Spécial Carac   | Préconisé
Sécuritaire  | 14 caractères  | Alpha Numérique Spécial Carac   | Préconisé

Bien sur la complexité est en prérequis (minimum). Aucune ne veux pas dire que tu ne peux pas en mettre.

PS : je n'ais pas regardé la faisabilité de ce que j'avance. mais on peux regardé ensemble si tu veux.

Voila voila.
Au plaisir
