### ISSUE TITLE
Allegement

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#499]
bonjour,

Ne devrait on pas supprimer 2 cases au moins là dessus

![image](https://user-images.githubusercontent.com/16939826/72824990-8990d800-3c76-11ea-9957-a3809c5a0c91.png)

**Comment by jipexu** [comment]
oui  je ne sais pas pourquoi on conserve 4 lignes ... alors qu'on peut écrire du html ... une case suffirait ?
historique ?

**Comment by Jireck-npds** [comment]
Ou 2 si la personne veux separé les informations du genre : 
1 case ==> les liens user
2 case ==> les liens admin

Il me semble que ces cases sont réactive au meta donc interressant si on les utilise dans une des cases
