### ISSUE TITLE
Step

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#50]
Hello
Pourrais tu faire un point sur ce qui reste a faire et ce qui bug ou a checker ?

**Comment by jipexu** [comment]
Salut Ji
Tellement de chose ... Je vais essayer de lister plus précisément ... je mettrai ici les bug confirmé et non encore résolu (la plupart date de REV 13 et avant) en ce moment c'est encore un peu instable car o chaque alpha de bootstrap on a quelques modif notamment sur des classes et autres bricoles ... je vais bientot sortir une nouvelle alpha ... et j'espère que bs sortira rapidement une beta à partir de la on pourra aussi sortir une beta pour que plus de monde puisse tester..

**Comment by Jireck-npds** [comment]
C'est la gros raison qui comme je te l'avais dit de ne pas integrer directement les classes dans le code. mais bon c'est fait.

**Comment by jipexu** [comment]
oui ca reste l'inconvenient de l'utilisation directe ... la plus simple mais la plus sensible aux changement du framework ...
