### ISSUE TITLE
Admin module

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#502]
Bonjour,
As quoi corresponds l'espece de diese ? 
![image](https://user-images.githubusercontent.com/16939826/89034867-1c9f7e80-d33a-11ea-88f4-1247121b210f.png)
![image](https://user-images.githubusercontent.com/16939826/89034905-2e812180-d33a-11ea-89dc-709af3a08aaa.png)
Il y aurai pas un probleme de proportion des icones

**Comment by jipexu** [comment]
Yo 
Non c'est volontaire ... arghh les goût et les couleurs l'espèce de dièse et de carré symbolisent des pseudo états du module ("compressé" avant l'installation + vert(installation)) et l'espèce de carré ("décompressé" quand il est installé + rouge(désinstallation si existe ou marqué comme désinstallé ) ...

**Comment by Jireck-npds** [comment]
Sur le "diese" il n'y a pas de hover pour savoir ce qu'il symbolise contrairement a la piece de puzzle qui veut dire installation.

ca veut dire quoi compressé ? 
Sans vouloir revenir sur les gout et les couleurs : un module doit avoir plusieurs etats simple : 
1) installé ou pas 
2) avec une installation ou desinstallation automatique
et a la rigueur un état "module obligatoire" 

J'ai aussi du mal avec l'etat de certains modules comme contact
![image](https://user-images.githubusercontent.com/16939826/89069917-5f7e4800-d374-11ea-9d18-1cf8e00b063e.png)
c'est fonctionnel et quand on clique dessus on a  : 
![image](https://user-images.githubusercontent.com/16939826/89070046-9bb1a880-d374-11ea-9634-0d35fd13dea1.png)

ce qui me semble pas normal.
