### ISSUE TITLE
Question Image

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#525]
Hello,

Pourquoi il y a les mêmes images dans themes\xxxx\images\forum\smilies alors qu'elles devraient (si je fais pas d'erreurs) etre dans \images\forum\smilies ?

**Comment by jipexu** [comment]
on a gardé les anciens smilies (dans \images\forum\smilies ) et en principe les bs themes elles sont différentes (avec aussi des noms différents ...?)

dans quel theme as tu trouvé les doublons (nom et contenu ?) si c'est le cas alors ouii elles ne devrait pas se trouver dans le theme ??

**Comment by Jireck-npds** [comment]
faites comme vous voulez de toutes façons les images sont tres difficiles a savoir ce qu'il représente car c'est des nom non explicite.
Je trouve juste que cela charge les thèmes pour rien ... a vous de voir après
