### ISSUE TITLE
minuscule et majuscule indifférenciées dans les login membre et admin

### ISSUE THREAD

**Issue by jipexu** [npds/npds_dune#54]
exemple : 
en admin avec 
Root root ou ROOT 
en membre 
# phr et PHR ou Phr 

login validé ...!!!

à fixer !!!!

**Comment by Jireck-npds** [comment]
Moi, je trouve cela bien afin de ne pas tomber dans les compte similaire ...

**Comment by Jireck-npds** [comment]
Juste pour discuter...
Voyons cela d'un coté sécurité.
Si tu différencie majuscule /minuscule tu va te retrouvé avec les mêmes problèmes que twitter qui son des comptes similaires et difficilement reconnaissance.

Coté pratique, indifférencié les majuscules et minuscules est un atout. même si l'affichage doit tenir compte des majuscules.

**Comment by jipexu** [comment]
fixed by : #373

**Comment by jipexu** [comment]
machine arrière <==

> Moi, je trouve cela bien afin de ne pas tomber dans les compte similaire ...

oui
ce comportement actuel est tout à fait correct et le seul qui peut fonctionner notamment à cause de la création des nombreux fichiers de conf basé sur le pseudo !! vouloir faire mieux serait faire moins bien ...

**Comment by jipexu** [comment]
pr:#390
