### ISSUE TITLE
Module-install Prefix

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#543]
Bonjour,

il doit y avoir un soucis avec la fonction nmig_WriteSql et nmig_AlertSql

Les symptômes lors que tu as une base prefixé : la derniere table (uniquement) est  double prefixé et cela pour tous les modules.
S'il y a 5 tables les 4 premieres sont bien prefixé, et la derniere doublé.

![image](https://github.com/npds/npds_dune/assets/16939826/f4dc3cf2-ab85-47ed-8ec4-cfcf4d5b72a9)

**Comment by jipexu** [comment]
et ce qui est écrit est ce que tu retrouve dans la bd ???

**Comment by Jireck-npds** [comment]
sauf pour le rev devant le create

**Comment by Jireck-npds** [comment]
en fait il fait bien une erreur  rev_CREATE

Une erreur est survenue lors de l'exécution du script SQL. Mysql a répondu :

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rev_CREATE TABLE rev_IF NOT EXISTS `rev_yo` ( `id` bigint(20) NOT NULL au' at line 1

**Comment by jipexu** [comment]
le sql de ton module est correct ?????

**Comment by Jireck-npds** [comment]
si tu as pas reconnu c'est le module gs_annonce pris sur GIT

**Comment by Jireck-npds** [comment]
https://github.com/npds/npds_annonces/blob/main/npds_annonces/install.conf.php

**Comment by Jireck-npds** [comment]
apres lecture de celui ci il manque : 
 global $NPDS_Prefix;
dans le fichier mais je ne sais pas si c'est obligatoire mais cela se fait sur t'autres install

**Comment by Jireck-npds** [comment]
je vois pas pourquoi ca met un $NPDS_Prefix devant le CREATE

**Comment by jipexu** [comment]
c'est quoi ta version de mysql ?

**Comment by Jireck-npds** [comment]
5.6.34

**Comment by jipexu** [comment]
faudra que je fasse des essai sur le labo ... tu peux modifier le conf en enlevant toute les concaténation du prefix ?

**Comment by jipexu** [comment]
de manière à ce que seul la ligne dans module install fasse son boulot ? ... et on verra si on a toujours l'erreur ...

**Comment by jipexu** [comment]
si tu install la galerie c'est pareil ?...

**Comment by Jireck-npds** [comment]
tu veux que je test quoi ? 
que l'install.conf est une requete sans NPDS_Prefix ?

**Comment by jipexu** [comment]
> faudra que je fasse des essai sur le labo ... tu peux modifier le conf en enlevant toute les concaténation du prefix ?

oui

> tu veux que je test quoi ?
> que l'install.conf est une requete sans NPDS_Prefix ? <== dans le conf

**Comment by Jireck-npds** [comment]
avec 
`
$sql = array("CREATE TABLE IF NOT EXISTS `recette` (
  `id` bigint(20) NOT NULL auto_increment,
  `id_cat` mediumint(11) default NULL,
  `id_ss_cat` mediumint(11) NOT NULL,
  `pseudo` varchar(25) collate utf8_unicode_ci NOT NULL,
  `titre` varchar(100) collate utf8_unicode_ci NOT NULL,
  `prepa` varchar(100) collate utf8_unicode_ci NOT NULL,
  `cout` varchar(100) collate utf8_unicode_ci NOT NULL,
  `text` mediumtext collate utf8_unicode_ci NOT NULL,
  `ingr` longtext collate utf8_unicode_ci NOT NULL,
  `recet` longtext collate utf8_unicode_ci NOT NULL,
  `img` varchar(20) collate utf8_unicode_ci NOT NULL,
  `en_ligne` tinyint(1) NOT NULL default '0',
  `acces` int(1) NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=0 ;",`

j'ai 

`rev_CREATE TABLE rev_IF NOT EXISTS `rev_recette` (
  `id` bigint(20) NOT NULL auto_increment,
  `id_cat` mediumint(11) default NULL,
  `id_ss_cat` mediumint(11) NOT NULL,
  `pseudo` varchar(25) collate utf8mb4_unicode_ci NOT NULL,
  `titre` varchar(100) collate utf8mb4_unicode_ci NOT NULL,
  `prepa` varchar(100) collate utf8mb4_unicode_ci NOT NULL,
  `cout` varchar(100) collate utf8mb4_unicode_ci NOT NULL,
  `text` mediumtext collate utf8mb4_unicode_ci NOT NULL,
  `ingr` longtext collate utf8mb4_unicode_ci NOT NULL,
  `recet` longtext collate utf8mb4_unicode_ci NOT NULL,
  `img` varchar(20) collate utf8mb4_unicode_ci NOT NULL,
  `en_ligne` tinyint(1) NOT NULL default '0',
  `acces` int(1) NOT NULL,
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=0 ;`

je vois un prefix de CREATE et un prefix sur IF et la table est bien prefixé

**Comment by Jireck-npds** [comment]
en enlevant IF NOT EXISTS l'affichage de ma requette est bonne 
J'ai donc en affichage : 
```
CREATE TABLE rev_recette (
  'id' bigint(20) NOT NULL auto_increment,
```

pour : 
```
global $NPDS_Prefix;
$sql = array("CREATE TABLE ".$NPDS_Prefix."recette (
```

pour la suite j'ai : 

`rev_CREATE TABLE rev_IF NOT EXISTS 'rev_recette_cate' (`

pour 
`"CREATE TABLE IF NOT EXISTS '".$NPDS_Prefix."recette_cate' (
  'id_cat' mediumint(11) NOT NULL auto_increment,`

**Comment by jipexu** [comment]
ok résolu -  me manque encore des tests avec base préfixée on avait donc une série de dysfonctionnement + un doublon de fonctionnement sur l'ajout des prefixes
- donc obligation pour les fichiers install_conf d'écrire les requêtes avec la concaténation de $NPDS_prefix
- suppression de la routine buggé (expression régulière ne prenait pas en compte les 'CREATE TABLE IF NOT EXISTS') qui ajoutait les prefixes dans module_install.php
