### ISSUE TITLE
impossible de mettre en résolu un post avec des /

### ISSUE THREAD

**Issue by jipexu** [npds/npds_dune#55]
renvoi un acces denied ..... 
par exemple je ne peux pas mettre en résolu ce post : 
[https://labo.infocapagde.com/viewtopic.php?topic=478&forum=9 ](url)
si j'enlève tout les slash dans le titre ça passe ... 

par contre je peux mettre en résolu ce post présent alors qu'il à lui aussi un slash ... 
[https://labo.infocapagde.com/viewtopic.php?topic=515&forum=9 ](url)

à investiguer ....

**Comment by Jireck-npds** [comment]
Pourra pas voir pour ceux qui n'ont pas de compte la bas
