### ISSUE TITLE
pas de chargement css du framework si le theme par défaut n'est pas skinable (_sk)

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#552]
hello,

voila a quoi ressemble le chat, c'est normal ?

<img width="283" alt="image" src="https://github.com/npds/npds_dune/assets/16939826/beeba925-bf6b-4bd4-9efd-7b49182e9c44">

**Comment by Jireck-npds** [comment]
et sur un site normal
<img width="366" alt="image" src="https://github.com/npds/npds_dune/assets/16939826/e035bf20-f076-4912-988b-3c8e797158f2">

**Comment by jipexu** [comment]
oui la deuxième version est ok mais la première version c'est pas ce que j'ai vu sur le chat de ton site ????

**Comment by jipexu** [comment]
<img width="760" alt="Capture d’écran 2024-05-08 à 19 28 56" src="https://github.com/npds/npds_dune/assets/328101/88a9b64f-527d-421e-84f8-def2f7dd1c14">

**Comment by jipexu** [comment]
mais du coup t'as pris une version du chat de la 16.8 ?

**Comment by Jireck-npds** [comment]
essaye avec l'url https://www.frigoristes.fr

**Comment by Jireck-npds** [comment]
apparament on a pas le meme visuel, j'ai essayer sous chrome et edge en anonyme ou en membre et rien

**Comment by jipexu** [comment]
testé sur https://www.frigoristes.fr/
c ok en membre !
mais pas en anonyme ou on n'as pas les css ....  ....

**Comment by Jireck-npds** [comment]
moi dans les 2 cas, j'ai style et chat et rien de plus

**Comment by jipexu** [comment]
???
la troisieme possibilité c'est que tu soit en anonyme mais connecté en admin (j'ai pas testé ça ??)
en tous cas je te confirme que  :  
en membre (sans connection admin) c ok
en anonyme (sans connection admin) c PAS ok
et donc avec une connection admin (pas testé ...)

inutile de te rappeler que les caches de tes navigateurs doivent être systématiquement désactivée/vidée et deux fois plutôt qu'une

**Comment by jipexu** [comment]
<img width="835" alt="Capture d’écran 2024-05-09 à 09 11 53" src="https://github.com/npds/npds_dune/assets/328101/6d42cc2b-e9c7-41d2-bcbe-0c41237d345d">

**Comment by jipexu** [comment]
ok je te comfirme qu'il y a bien un probleme ! 
- pour faire cours il semble que l'on est enlevé le chargement de la css de bootstrap en dur pour un chargement de la feuille de style par la fonction import_css() hélas on a pas tenu compte des themes par default qui n'ont pas de skin .....
le bloc de condition ligne 29 à 43 ne tiens pas compte d'un theme par defaut sans skin ... ce qui ne plait pas à la fonction import_css () ... utilisé pour le chargement ...

et donc en réparation temporaire il faut remettre en dur dans chatinput.php juste sous la ligne 47 (echo import_css ...)

`   echo '<link rel="stylesheet" href="lib/bootstrap/dist/css/bootstrap.min.css">';
`

**Comment by jipexu** [comment]
ok à la fin du bloc de condition (ligne 29 43) il faut rajouter ça
`   $skin = $skin =='' ? 'default' : $skin;
`
et là import_css est ok ... 
donc pas besoin de charger en dur (correction mentionné ci dessus n'est plus nécéssaire...)

dis moi si c'est ok ? pour moi testé et semble ok dans tous les cas ...

**Comment by Jireck-npds** [comment]
hello jpb,

Jai fait la modif et cela marche.
Par contre, quand je clique sur le smiley, il y a un ascensuer qui s'affiche quand on survole le smiley ou quand on clique dessus
<img width="284" alt="image" src="https://github.com/npds/npds_dune/assets/16939826/09e35326-1da3-4047-b275-91d5722dbd6b">

**Comment by Jireck-npds** [comment]
image au survol 
<img width="289" alt="image" src="https://github.com/npds/npds_dune/assets/16939826/c7f6ab84-679e-499b-b99b-583aaaef4d78">

**Comment by Jireck-npds** [comment]
sans sur vol
<img width="287" alt="image" src="https://github.com/npds/npds_dune/assets/16939826/b85e05eb-47df-4add-8230-d8383fc5a101">

**Comment by Jireck-npds** [comment]
d'ailleurs c'est marrant c'est pas tout le temps

**Comment by jipexu** [comment]
probablement un survol un peu trop appuyé !!

**Comment by jipexu** [comment]
good closed with https://github.com/npds/npds_dune/commit/981eb8cf03d6d64f1db831f6c654899197e7658d
