### ISSUE TITLE
Requete sql insert des options défaillante quand sondages avec noms identiques

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#553]
Hello
Le problème est lors de l'enregistrement des options du sondage dans poll_data.
Il n'enregistre pas les options

Le poll est bien enregistrer dans poll_desc

**Comment by jipexu** [comment]
Plus de précision ? car pour moi c'est fonctionnel ... (testé : modfication des options et enregistrement ok dans la db ...) c'est un nouveau sondage ??
rappel moi la version de ton sql ??

**Comment by Jireck-npds** [comment]
mysql 5.7
php 7.4

**Comment by Jireck-npds** [comment]
en fait, j'ai p'tre la solution.
J'ai créer un nouveau sondage avec le titre d'un ancien puisque c'est le meme sujet.
par contre, là j'ai refait la manip en changeant le titre et c'est bon

**Comment by jipexu** [comment]
donc pas d'erreur réelle ... ?

**Comment by Jireck-npds** [comment]
Ben si ... si tu as 2 sondages qui ont le même nom cela semble posé problème

**Comment by jipexu** [comment]
ah voilà qui est plus précis ! je vais tester dans ce sens ....

**Comment by jipexu** [comment]
confirmé !
ligne 106 de admin/polls.php
remplacer
`   $result = sql_query("INSERT INTO ".$NPDS_Prefix."poll_desc VALUES (NULL, '$pollTitle', '$timeStamp', 0)");
`
par

`   $result = sql_query("INSERT INTO ".$NPDS_Prefix."poll_desc VALUES (0, '$pollTitle', '$timeStamp', 0)");
`

**Comment by jipexu** [comment]
ceci semble ok !?...
remplacement de la méthode d'obtention de l'id qui était basé sur le nom ... par `$id = sql_last_id();` 

```
function poll_createPosted() {
   global $maxOptions, $pollTitle, $optionText, $poll_type, $NPDS_Prefix;

   $timeStamp = time();
   $pollTitle = FixQuotes($pollTitle);
   $result = sql_query("INSERT INTO ".$NPDS_Prefix."poll_desc VALUES (0, '$pollTitle', '$timeStamp', 0)");
   $id = sql_last_id();
   for ($i = 1; $i <= sizeof($optionText); $i++) {
      if ($optionText[$i] != '')
         $optionText[$i] = FixQuotes($optionText[$i]);
      $result = sql_query("INSERT INTO ".$NPDS_Prefix."poll_data (pollID, optionText, optionCount, voteID, pollType) VALUES ('$id', '$optionText[$i]', 0, '$i', '$poll_type')");
   }
   Header("Location: admin.php?op=adminMain");
}

```

**Comment by jipexu** [comment]
closed with https://github.com/npds/npds_dune/commit/7aeaef0533da58d68cb297ed86e0182cb6c482af
