### ISSUE TITLE
Impossible installer modules16.8

### ISSUE THREAD

**Issue by PUJADER** [npds/npds_dune#554]
Bonjour, après installation sans soucis de la version 16.8 impossible de trouver un module pourtant poser dans le dossier modules, et donc de l'installer

**Comment by jipexu** [comment]
Bonjour quel module ?

**Comment by PUJADER** [comment]
Bonjour Jipexu ;-) , bon j'ai relancé ce matin usbwebserver et ce matin il me trouve le dossier , j'ai bien mon module qui apparait. J'impute donc cela à webserver mais je ne comprends pas pourquoi , j'ai été vérifier mon module et je vois rien qui fait que ... je continue mes tests et dsl pour ça .Ce qui me paraissait bizarre hier c'est que je voyais monmodule_template et pas celui que j'avais mis ... le cache de la clé USB ? je pense pas non plus. je vais voir avec d'autres modules voir si j'ai le même soucis .

**Comment by PUJADER** [comment]
j'ai trouvé mdr ... Mon erreur est d'avoir travaillé sur deux disque dur ...
je risquais pas de voir le module ...
C'est bien de faire des sauvegardes , mais c'est bien aussi de pas se tromper de disque lol

**Comment by jipexu** [comment]
ok alors tout va bien lol !
