### ISSUE TITLE
forum arbre toggle systeme not work

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#64]
Salut Jpb

Sur le labo de phr, quand tu post sur le viewtopicH il y a un soucis ... ou pas .
http://labo.infocapagde.com/viewtopicH.php?topic=567&forum=38#last-post

Je te cite je poste et je rempli l'anti-spam ==> pas de post visible ==> SC ? 
On voit que anonyme a repondu mais on ne voit pas la reponse...

De plus, quand tu appuis sur la fleche du bas pour afficher la reponse ==> rien ne s'affiche 
La fleche passe vers le haut, on clique  pour cacher la reponse (non visible) c'est ton poste qui disparrait et impossible de le faire reapparaitre pas de fleche rien ... 

Voila

**Comment by jipexu** [comment]
oui c'est encore instable (désimplémentation de togglediv en cours et réimplémentation  ...) mais ce n'est pas l'antispam ... juste le systeme de toggle qui fonctionne mal ...

**Comment by jipexu** [comment]
fixed ...
