### ISSUE TITLE
chargeur js de pages.php bug avec array de css

### ISSUE THREAD

**Issue by jipexu** [npds/npds_dune#65]
[Rev13 bug]=>[Rev16 bug]
contexte et exemple : 
dans pages.php mettre pour les css du chat un tableau array("chat.css","boostrap.css") au lieu de chat.css seul ( ce qui est permis) 

mais PHP retourne logiquement une erreur utilisation de la fonction substr sur un tableau ...

et on a cruellement besoin de cette fonction ...

**Comment by Jireck-npds** [comment]
Je ne comprends pas ton bug.. ?

**Comment by jipexu** [comment]
le fait de mettre un array de css génère une erreur PHP ... si il n'y a qu'une feuille de style c bon si c'est un array cela ne fonctionne plus car dans le code on applique un substr (qui ne s'applique que sur les chaine de caractère pas sur les tableau) car la variable est un tableau (comme défini dans page.php ....

**Comment by Jireck-npds** [comment]
je ne vois pas ou tu fais un sustr ? 
305    // Chargeur de CSS via PAGES.PHP 
306    if (array_key_exists($pages_ref,$PAGES)) { 
307       if (array_key_exists('css',$PAGES[$pages_ref])) { 
308          $css_pages_ref=$pages_ref; 
309          $css=$PAGES[$pages_ref]['css']; 
310       } else { 
311          $css_pages_ref=''; 
312          $css=''; 
313       } 
314    } else { 
315       $css_pages_ref=''; 
316       $css=''; 
317    } 
318  
319    // Mod by Jireck - Chargeur de JS via PAGES.PHP 
320    if (array_key_exists($pages_ref,$PAGES)) { 
321       if (array_key_exists('js',$PAGES[$pages_ref])) { 
322          $js=$PAGES[$pages_ref]['js']; 
323          if ($js!='') { global $pages_js; $pages_js=$js; } 
324       } else { 
325          $js=''; 
326       } 
327    } else { 
328       $js=''; 
329    }

**Comment by jipexu** [comment]
non pas là ...
mainfile.php
         $op=substr($tab_css,-1);
ligne 2898 et 2900

**Comment by jipexu** [comment]
pour les page qui ne font pas appel au header

**Comment by Jireck-npds** [comment]
Oui les deux ou plus  css doivent avoir soit un + soi un -  afin de savoir si on ajoute ou retranche les css
le foreach te ramene bien un string normalement...

**Comment by Jireck-npds** [comment]
A moins que ce soit le import_css qui change les quotes qui posent probleme

**Comment by jipexu** [comment]
je pense que c'est la boucle 
foreach ($css as $k=>$tab_css) {  qui transforme $tab_css en array
si on fait
foreach ($css as $tab_css) { ...  on devrait revenir sur string

**Comment by jipexu** [comment]
je vais tester ça ...

**Comment by Jireck-npds** [comment]
C'est cool quand on reflechis a plusieurs, on arrive a des solutions et Presque des resolutions ;-)
Super job jpb

**Comment by jipexu** [comment]
oui c'est sur des bon outils et des bon cervaux lol
