### ISSUE TITLE
Popup user

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#66]
Il serait bien que lorsqu'on clique sur le deuxieme avatar pour avoir le popup, le premier se ferme

**Comment by jipexu** [comment]
oki je vais voir - (pa si simple à première vu ..)

**Comment by jipexu** [comment]
je vais essayer en rajoutant un data-trigger="focus"
et un bout de js en plus 
```
$('.popover-dismiss').popover({
  trigger: 'focus'
})
```

**Comment by jipexu** [comment]
bon c ok ca fonctionne
et c'est bien mieux comme ça ...
 il faut que je le propage le data-trigger="focus" dans les fichiers concernés
