### ISSUE TITLE
Reseaux sociaux

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#67]
Je viens de faire un test et j'ai rempli les reseau sociaux d'un user de test.

Quand je clique sur l'avatar rien n'apparait .

Faut il activer quelque chose en particulier ?

**Comment by jipexu** [comment]
admin.php?op=Configure
est ce que  la description simplifié des utilisateurs est à non ?

**Comment by Jireck-npds** [comment]
la description simplifié des utilisateurs est à oui.
Mais je ne vois pas pourquoi la description simplifié jouerais la dessus.

Pour moi, soit tu active les reseau sociaux soit tu ne l'active pas c'est independant de la description simplifié meme s'il me semble que historiquement l'extends des champs dependait de cela

**Comment by jipexu** [comment]
oui c'est implémenté comme ça ... historiquement ce n'était pas seulement les champs extend mais aussi tous les anciens champs (aim, icq ... ...) donc j'ai gardé comme c'était ...

**Comment by Jireck-npds** [comment]
je pense qu'il faut change cela ....
Apres c'est comme tu veux ...
Je trouve aussi dommage que les liens soit uniquement dans le popup de l'avatar et non comme c'etait avant et quand on reduit le format genre phone on passé par l'avatar.
c'est a dire qu'on est obliger de faire une action pour y accede et sur grand ecran cela comble les espaces vides ...

Purement mon avis, a toi de voir comment tu fais

**Comment by jipexu** [comment]
- oui on pourra réfléchir pour le shortuser (donc si on prend le problème à l'envers à quoi doit servir cette variable ???)
- pour le popover (l'idée c'était d'alléger aérer le forum ...) car avant c'était tout mélangé les actions et infos du post du sujet du membre .... une solution intermédiaire grand et petit média peut effectivement aussi être envisagée

**Comment by Jireck-npds** [comment]
Pour le popover, l'idée est bonne mais restons pragmatique sur certains elements : 
La qualité (member_qualify "a la base") du user n'est plus indiqué ....
Je prends l'exemple du labo (où je suis toujours restraint) on ne voit pas que toit tu est "Dev Team" ce qui quelque part fait de ton  post un reply standard alors que cette qualification aide....
Je te parle de cela car, par exemple, sur les frigoristes certains members sont qualifie de modo ou de membre certifié qui donne un valeur a la reponse.
-------------------------------------------
c'est un peu la meme chose pour les reseau sociaux visible ou pas .... 
quand la reponse est bonne, on a envie d'aller voir son site ou son profil linkedin ou autre..

Oui, pour la variable shortuser il faut voir maintenant a quoi elle sert...
Je n'ai pas assez de connaissance sur les modifications que tu as realizer pour te faire un retour...
Veux tu que je regarde ?

Juste un dernier retour : nickel pour les popup avatar. de plus cela permet de fermeer la fenetre en cliquant a coté a lieu de cliquer dessus .... Great Job !!!
