### ISSUE TITLE
Chargement JS CSS

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#68]
Ca serait pas mal  de ne charger que ce qui est utile... via pages.php a la racine des themes.
la lib js colorpicker chargé en index.php ... ca fait mal au *ul entre autres...

Je vais regardé comment faire car on en avait discuter mais il me semble que c'etait .... je ne sais pluhs ...

**Comment by jipexu** [comment]
pour colorpicker je vais la descendre dans page.php  juste (de mémoire) la ou elle est utilisé dans geoloc pour l'instant ...  (la c'est facile)

oui on en avait discuté mais on a toujours pas de solution cohérente ..
je te donne un exemple comment éviter de charger tiny  (320k) dans toutes l'admin alors que l'on ne s'en sert que sur certaines pages ? ... (pour moi c'est probablement buggé et y'a pas moyen de le réaliser en tous cas j'ai essayer par page.php et je n'y suis pas parvenu ! ...

**Comment by Jireck-npds** [comment]
Oui pour moi pages a certains bugs mais faudrait que je me replonge dedans ...
Y'a colorpicker mais aussi datepicker, hightlight ainsi que les css associées.

Concernant tiny 320K c'est vrai que c'est problematique... faut que je regarde si tu veux ...

Pour moi, tout doit passer par pages.php (racine) qui est le chargeur css et js modulable.

La coorection aussi qu'il faudrait faire etant un architecture correct des css et js du genre : 

lib / css
lib / css / bootstrap
lib / css / bootstrap / table
lib / css / bootstrap / datepicker
lib / css / bootstrap / hightlight
lib / css / jquery 
lib / css / jquery / plugin_x

et la meme pour les js.
lib / js
lib / js / bootstrap
.....
Qui donne une logique a la structure

**Comment by Jireck-npds** [comment]
Bon après lecture, il y a une erreur 
// Initialisation de TinyMce
   global $tiny_mce,$tiny_mce_theme,$tiny_mce_relurl;
   if ($tiny_mce) {
      **if (array_key_exists($pages_ref,$PAGES)) {
         if (array_key_exists('TinyMce',$PAGES[$pages_ref])) {**
            $tiny_mce_init=true;
            if (array_key_exists('TinyMce-theme',$PAGES[$pages_ref]))
               $tiny_mce_theme=$PAGES[$pages_ref]['TinyMce-theme'];
            if (array_key_exists('TinyMceRelurl',$PAGES[$pages_ref]))
               $tiny_mce_relurl=$PAGES[$pages_ref]['TinyMceRelurl'];
         } else {
            $tiny_mce_init=false;
            $tiny_mce=false;
         }
      } else {
         $tiny_mce_init=false;
         $tiny_mce=false;
      }
   } else {
      $tiny_mce_init=false;
   }
