### ISSUE TITLE
Faille de sécurite npds_annonces

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#98]
Jpb,

Si tu n'as touché que annonce_form, il existe toujours des failles de sécu.

Mais tu pourras t'en occupé plus tard avant de valider le module

**Comment by jipexu** [comment]
Probablement ... j'ai modifié annonce form qui était grand ouvert mais aussi le traitement de certaines  requêtes ... mais pour l'instant je ne sais pas si et où sont les autres failles (je me suis juste concentré sur celle-ci)...  Comme je te l'ai dit dans le forum je suis preneur pour d'autres info si tu en sais plus. Je vais mettre à jour la branche modules de github avec ce que j'ai sur le labo ...

**Comment by jipexu** [comment]
bon il semble qu'il y ai exactement la même dans modif_ann.php ... tu confirmes ?

**Comment by Jireck-npds** [comment]
Concentre toi sur le core de npds.
je ne donnerais pas plus d'informations que cela.
Raison : Ca doit être à cause de la nouvelle personne qui développe ce module.
D'ailleurs je me demande pourquoi c'est toi qui fix le module....

Faire un branche Git pour les modules... tu peux mais je n'y participerais pas .... on risque de me le reprocher.
de plus, comme deja dit, vous desiriez des retours sur les modules : 
- mettez les en DL et pas en privé et ouvrez un forum ou vous voulez avec les droits de poster en anonyme.
ca evitera le muselage de ce que ecrive les gens.

**Comment by Jireck-npds** [comment]
maintenant fais comme tu pense ...
tu peux meme clore cet issue

**Comment by Jireck-npds** [comment]
Oui un fonctionnel existait depuis longtemps c'est pour cela que je disais de prendre la derniere version ...
De plus cela amenait des ameliorations.
Mais pour cela, il aurait fallut me contacter et me demander ..
Maintenant impossible de voir le code qui date de 12-04-2016 00:00

**Comment by jipexu** [comment]
on a pas les clefs de tes placards !  juste l'accès à modules où sont censés se trouver les modules ...

j'avais téléchargé ce patch (qui d'après moi ne fonctionne pas non plus)... du coup il s'agit de la meme faille .. celle-ci est ok mais il y en a une autre (que je n'ai pas testée vraiment) mais l'écriture du script est à peu près similaire et permet à un anonyme(robot ou humain) de pouvoir essayer de bricoler les urls pour injecté dans la base ...

**Comment by Jireck-npds** [comment]
Comme je l'ai dit certains modules etait telechargeable sur NPDS et modules (forum). vous avez telechargé la version en DL sur modules ==>  légitime. 
et quand je vous l'ai signalé, c'est parti en noeud de boudin ... bref on s'en fout maintenant.

Une des failles de sécurité est dans annonce_form ==> oui l'anonyme pouvais posté des annonces sans autorisation.
J'avais corrigé cela dans la version et basculé d'ailleurs annonce_form dans fonction.php (à faire je pense).

Je n'ai pas connaissance du patch dont tu parles. donc ???

**Comment by Jireck-npds** [comment]
finalement je viens de rechercher et si c'est la version que j'avais fait oui 

La faille est corrigé mais pas repris dans votre module

**Comment by jipexu** [comment]
si celle-ci est corrigé (la correction est au meme endroit dans le fichier et a peu près similaire à ton patch) 
Mais on en a une autre !

**Comment by jipexu** [comment]
http://modules.npds.org/download.php?op=mydown&did=170 
sur ce patch

**Comment by Jireck-npds** [comment]
oui ligne 42

**Comment by Jireck-npds** [comment]
Correct ?
Mais 
J'en suis sur

**Comment by jipexu** [comment]
alors je te le redis ce patch (ligne 42) ne fonctionne pas ...!

**Comment by Jireck-npds** [comment]
je ne vois pas pourquoi mais bon si tu es sur ....
Fais ...
Juste pour info : Quand j'ais fait ce patch, dev m'a confirmé ma correction ... il a ptre loupé un truc et moi aussi...
Donc go ...
Je suis preneur de ta solution.

**Comment by jipexu** [comment]
la solution est dans le fichier sur github et sur le labo
pourquoi ca ne fonctionne pas et comment un bot peut contourner et trouver la faille

tu definis le user dans l'url $user= et un $id_user= et un $prix=123
comme ceci le isset($user) est JUSTE le prix est JUSTE et le id_user vide DONC égal au cookie[0] qui est vide AUSSI car quand tu es en anonyme il n'existe PAS !

essai une url de ce type et tu verra que la base est renseigné même quand tu es en anonyme ... donc un robot peut aisément le faire ... c'est ce qui c'est passé chez chouette par exemple ....

**Comment by Jireck-npds** [comment]
1) $id_user ne peut etre vide
**and (trim($id_user)!="")**

**Comment by jipexu** [comment]
Sur github modules dans le fichier à la même ligne à peu pres

**Comment by Jireck-npds** [comment]
C'est à peu pres la meme chose....
Ma solution marchait.
Maintenant chacun voit sa solution

**Comment by jipexu** [comment]
non !
test des urls de ce type et tu verras qu'elle ne fonctionne pas !

modules.php?ModPath=npds_annonces&ModStart=annonce_form&op=soumettre&prix=123&user=&id_user=

**Comment by jipexu** [comment]
en fait ... 
c'est l'utilisation de redirect qui pose problème car elle ne peut en aucun cas arreter l'interprétation du code php situé en dessous des conditions !! ....!  car c'est du javascript  !.... donc si l'url a les conditions requise tu renseigne la base ...

**Comment by jipexu** [comment]
en clair (comme les conditions sont écrites) si les variables ne sont pas bonne ont va être redirigé par js vers une autre page mais cela n'empeche pas l'execution de la requete ...

**Comment by Jireck-npds** [comment]
Bref la solution est bonne mais le deny sur condition n'est pas bon ...
donc fallait juste rajouter un die

**Comment by jipexu** [comment]
merci de réouvrir quand nécessaire ce post dans modules ..
