### ISSUE TITLE
Obligation Mail 

### ISSUE THREAD

**Issue by Jireck-npds** [npds/npds_dune#99]
Obligation de remplir le champs Compte Email (provenance)

 Alors que Notifier les nouvelles contributions par E-mail est à non 

A moins que fixé dans la V6

**Comment by jipexu** [comment]
dans quel contexte quel url ??

**Comment by Jireck-npds** [comment]
Preferences

**Comment by jipexu** [comment]
vu mais il semble que cette variable serve aussi ailleurs et soit nécessaire (download...) broken links
